### ISSUE TITLE
Modify Radio Targets to linkify with org-roam 

### ISSUE THREAD

**Issue by CestDiego** [org-roam/org-roam#1010]
### Brief Abstract
Similar to how you hacked org-capture-templates, perhaps doing something with the automatic linking with radio targets could be super useful: https://orgmode.org/manual/Radio-Targets.html

- [X] No similar feature requests

**Comment by Anton-Latukha** [comment]
Current Org-mode solution worked pretty great and scaled well up to the point:
In note taking with regular Org-mode radio targets I've hit the hard limit on C funtrion regex length: https://github.com/Anton-Latukha/Fundamental-Haskell/tree/06755118725ad7da122a4c9dc21e2d144a61fa34
So large cross-linked files now can not load into Org-mode.

So regular Org-mode radio target cross-linkage works for content up to ~150 pages.

Org-roam probably can solve this in a better way.

**Comment by CestDiego** [comment]
I see, The link you posted goes to some Haskell repository, I think that's a mistake, but other than that. I'd love to learn more about the issue, hope that when org-roam figures something out, it can be upstreamed to org-mode.

**Comment by Anton-Latukha** [comment]
It is not a Haskell repository - it is a book about Haskell written in Org-mode, it is just a good example of the power of radio targets for Zettelkasten, probably I should've linked to [https://raw.githubusercontent.com/Anton-Latukha/Fundamental-Haskell/master/README.pdf](PDF) version. - The thing there is that almost all cross-linkage is made automatically by radio targets, if I would maintain links myself - that project would not be possible - I'd would spend month only on cross-linking the topics, and every new entry would'be required a new pass over the all what is written to insert links to the entry I just created.

Manual cross-linkage in Zettelkasten takes a lion's share of the time, that time better to be spent concentrating on the topic writing at hand. And after awhile no-one who writes Zettelkasten - remembers all ideas and content entered into Zettelkasten several years ago - so if links are only manually done - no one links to the old ideas/content, and the cross-linkage and combining of ideas is what Zettelkasten is about.

In Org-mode radio targets work simply - they work only inside the scope of a buffer/file. When file is opened - Emacs Org-mode parses the whole file for `<<<targets>>>` , and then builds a one huge regex from all of them. And that regex in 150 pages gets to the C function hard limit.

Org-roam can use the same syntax Org-mode already uses and allow the Org-mode to handle the file scope, and extend it with additional Roam abilities. Due to design differences, Org-Roam can employ way better approach to handling links, and handle them across the Zettelkasten, giving the powerful option of automatic source referencing. Because Org-Roam builds & keeps and relies on the DB - information on radio targets can be gathered and kept in the DB. It basically starts from something like adding target names as link names into the DB.

**Comment by jethrokuan** [comment]
Org-roam v2 only supports `id` links, and will only support `id` links.

**Comment by Anton-Latukha** [comment]
Well, true. Someone needs to implement it before it would work & it probably requires a number of architectural shifts.

Thank you for all the hard work on the project, & we need to remember that it is all a gift to us.

**Comment by kjelljorner** [comment]
I second that this would be a great idea. Now that org-roam supports working with headlines in a single document, adding support for radio targets would be a killer feature.

**Comment by salutis** [comment]
> radio targets would be a killer feature.

+1 here.  I decided to stop using Org Roam until it supports radio targets or some other kind of automatic linking.  Let the computer do the work!

**Comment by lytex** [comment]
I honestly think is too much trouble considering how easy it is to turn this "unlinked references" into linked references

Simply replace every occurrence of "very specific concept" with "[[id:459717b2-c6c7-4a5a-a1dc-612b2b25886f][very specific concept]]" or whatever id in the current document

The replacement isn't even across different files since radio targets only work inside a given document, and if you want to search across multiple files you have, well, unlinked references
