### ISSUE TITLE
empty backlinks

### ISSUE THREAD

**Issue by lenient7** [org-roam/org-roam#1092]
### Description
Backlinks are empty for all files.

#### Steps to Reproduce
1. Load Emacs
2. Run 'org-roam-mode'
3. Run 'org-roam-find-file' to open any roam files
4. Run 'org-roam' to open backlinks buffer.

#### Backtrace
I did not get any errors. However, I could trace it back to 'org-roam-buffer--insert-backlinks ()'.

In line 156,             (titles (with-current-buffer org-roam-buffer--current
                                           (org-roam--extract-titles)))
returns as nil. Because 'file-path' is retrieved fine, I could use 
                              (backlinks (org-roam--get-backlinks file-path))
to make it work, instead of (backlinks (org-roam--get-backlinks (push file-path titles))

#### Expected Results
jordan_stresses_1962

* 1 Backlink
** [[file:/home/huy1/local/org/mindmap/20200811160921-inflation_contained_volume.org][20200811160921-inflation_contained_volume]]
*** Thin-walled pressurized volume
[[file:/home/huy1/local/org/mindmap/jordan_stresses_1962.org][jordan_stresses_1962]]

#### Actual Results
jordan_stresses_1962

No backlinks! 

### Environment
Copy info below this line into issue:
- Emacs: GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30, cairo version 1.15.10)
 of 2020-09-06
- Framework: N/A
- Org: Org mode version 9.3.8 (9.3.8-elpaplus @ /home/huy1/.emacs.d/elpa/org-plus-contrib-20200907/)
- Org-roam: 1.2.1

**Comment by myshevchuk** [comment]
Is your `org-roam-directory` accidentally a symbolic link?

**Comment by lenient7** [comment]
No, it is not. I read that issue, and double-checked it.

 

Hojae

**Comment by myshevchuk** [comment]
I cannot reproduce it with the steps you provided. That is the backlinks do show up. Must be something else in your config. Stale *.elc files?

**Comment by myshevchuk** [comment]
Moreover, this doesn't make much sense:
> In line 156, (titles (with-current-buffer org-roam-buffer--current
(org-roam--extract-titles)))
returns as nil. Because 'file-path' is retrieved fine, I could use
(backlinks (org-roam--get-backlinks file-path))
to make it work, instead of (backlinks (org-roam--get-backlinks (push file-path titles))

Try evaluating this:
``` elisp
(let ((titles nil)
        (file-path t))
  (message "%s" titles)
  (message "%s" file-path)
  (message "%s" (push file-path titles)))
```

You get 
> nil
> t
> (t)

`org-roam--get-backlinks` automatically converts non-list to a list, so `(org-roam--get-backlinks "file")` and `(org-roam--get-backlinks (push "file" titles))` where titles is nil should be equivalent. Yet it is not. I'd say it's a stale config.

**Comment by lenient7** [comment]
Thank you for the follow-up. I am getting the exactly same result by
evaluating the suggested lines. I will keep looking for what is wrong with
my set-up.

Can you kindly elaborate on 'stale config'? Do you mean init config files?

By the way, thank you for developing and maintaining this fantastic package!

Hojae

**Comment by lenient7** [comment]
I want to add that I also have to comment out lines;
(titles (with-current-buffer org-roam-buffer--current
            ;;           (org-roam--extract-titles)))

Otherwise, no backlink shows up. It appears that 'titles' gets 'nil' and
the code jumps to the line of  (insert "\n\n* No ref backlinks!").

I will keep digging.

Thanks!

**Comment by myshevchuk** [comment]
> Can you kindly elaborate on 'stale config'? Do you mean init config files?

Stale config means some parts of your system are outdated and/or corrupted. 

Usually, this happens when one has external packages loaded improperly during Emacs startup and attempts to upgrade these packages. Pieces of both new and old code of a package or several packages that are interconnected through shared libraries are loaded simultaneously during compilation, which results in a corrupted byte code, which in turn manifests itself in during the following Emacs launches in an unpredictable manner leading to a weird behaviour whose cause can hardly be traced. Sometimes, errors during compilation happen even when the package was loaded properly before the update.

If your personal configuration file (.emacs, init.el, config.el, etc.) looks fine, then quit Emacs, delete all external packages and restart Emacs to get them installed afresh. If the behaviour persists, then disable your personal config (comment it out) leaving only the bare minimum, restart Emacs and check whether you can reproduce the issue. Then re-iterate this procedure, re-enabling each time your config piece by piece until you find the offender.

Doing this pay special attention to how you load Org Roam. Check upon startup the value of `org-roam-directory`. You can also try to remove `org-roam.db` and run `M-x org-roam-db-build-cache` to rebuild the cache. You should actually start with this.

> I want to add that I also have to comment out lines;
(titles (with-current-buffer org-roam-buffer--current
            ;;           (org-roam--extract-titles)))

Yeah, that makes sense. I did not pay attention this is wrapped into `if-let*`. Anyway, it seems `org-roam--extract-titles` fails to find any titles in your files. Check the value of `org-roam-title-sources`, since it is used to call several different functions to search for the title.

> By the way, thank you for developing and maintaining this fantastic package!

Thank you for your kind words, but all the thanks should go to Jethro and Zaeph.

**Comment by lenient7** [comment]
Thanks! As I comment below, it was because of a setting
org-roam-title-sources as '(alias) in my config. Keeping it as the default
makes things back to normal!

On Sat, Sep 12, 2020 at 5:10 PM Mykhailo Shevchuk <notifications@github.com>
wrote:

> Can you kindly elaborate on 'stale config'? Do you mean init config files?
>
> Stale config means some parts of your system are outdated and/or corrupted.
>
> Usually, this happens when one has external packages loaded improperly
> during Emacs startup and attempts to upgrade these packages. Pieces of both
> new and old code of a package or several packages that are interconnected
> through shared libraries are loaded simultaneously during compilation,
> which results in a corrupted byte code, which in turn manifests itself in
> during the following Emacs launches in an unpredictable manner leading to a
> weird behaviour whose cause can hardly be traced. Sometimes, errors during
> compilation happen even when the package was loaded properly before the
> update.
>
> If your personal configuration file (.emacs, init.el, config.el, etc.)
> looks fine, then quit Emacs, delete all external packages and restart Emacs
> to get them installed afresh. If the behaviour persists, then disable your
> personal config (comment it out) leaving only the bare minimum, restart
> Emacs and check whether you can reproduce the issue. Then re-iterate this
> procedure, re-enabling each time your config piece by piece until you find
> the offender.
>
> Doing this pay special attention to how you load Org Roam. Check upon
> startup the value of org-roam-directory. You can also try to remove
> org-roam.db and run M-x org-roam-db-build-cache to rebuild the cache. You
> should actually start with this.
>
Thank you for the very detailed explanation. I tried to run org-roam with a
bare-minimum config as well as wiping off .emacs.d/elpa directory and
installing necessary packages only.

> I want to add that I also have to comment out lines;
> (titles (with-current-buffer org-roam-buffer--current
> ;; (org-roam--extract-titles)))
>
> Yeah, that makes sense. I did not pay attention this is wrapped into
> if-let*. Anyway, it seems org-roam--extract-titles fails to find any
> titles in your files. Check the value of org-roam-title-sources, since it
> is used to call several different functions to search for the title.
>
This was it! I had a line in my config that resetting
'org-roam-title-sources' to '(alias) only. I do not remember when and why I
added that line, but keeping it as the default makes things work fine.
Thank you very much!

**Comment by myshevchuk** [comment]
Good to hear your issue's solved!
