### ISSUE TITLE
`org-roam-complete-everywhere` creates a link that does not follow `org-roam-link-title-format`

### ISSUE THREAD

**Issue by brabalan** [org-roam/org-roam#1197]
#### Steps to Reproduce

1. set `(setq org-roam-link-title-format "§:%s")`
2. start typing the name of a title of a note
3. choose a completion
4. `[[roam:Org Roam]]` is inserted instead of `[[roam:Org Roam][§:Org Roam]]`

### Environment

- Emacs: GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.22, cairo version 1.17.3)
 of 2020-08-28
- Framework: Doom
- Org: Org mode version 9.4 (nil @ /home/schmitta/.emacs.d/.local/straight/build/org-mode/)
- Org-roam: 1.2.2

**Comment by jethrokuan** [comment]
#1199 addresses the problem, but not in the way you expect.

`[[roam:]]` links are meant to be description-less. However, that particular `roam:` link used to replace to just `Org Roam`, now it replaces to `§:Org Roam` as per `org-roam-link-title-format`.

One reason we don't autocomplete the description is that it's possible to want to add the completion for a headline within that note as well. There's little reason to prepend add a description to `[[roam:]]` links, since they're at this moment not exportable, and `[[roam:]]` seems like it would provide sufficient distinction.

Also, it's probably neater to customize the `org-roam-link` related faces to achieve visual distinction, rather than use a symbol.

**Comment by brabalan** [comment]
Thank you for the fix and the suggestion. I've changed the face as suggested.
