### ISSUE TITLE
 all files become unreadable when building cache after emacs 27.1 upgrade

### ISSUE THREAD

**Issue by lsiksous** [org-roam/org-roam#1231]
All files become unreadable when building cache after emacs 27.1 upgrade on macOs.

db-clear then db-build-cache.

No error but lots and lots warning !

- Emacs: GNU Emacs 27.1 (build 1, x86_64-apple-darwin18.7.0, Carbon Version 158 AppKit 1671.6)
 of 2020-10-31
- Framework: N/A
- Org: Org mode version 9.4 (9.4-27-g47bf60-elpaplus @ /Users/lss/.emacs.d/elpa/org-plus-contrib-20201026/)
- Org-roam: 1.2.2

**Comment by d12frosted** [comment]
Hey @lsiksous ,

I believe there are many people already using `org-roam` with Emacs 27.1 or even 28 (me included). I suspect it might be related to something else 😸 Could you please share the warnings?

**Comment by lsiksous** [comment]
😃  Yes I know ! But maybe less with emacs mac port and last melpa version of org-roam installed two days ago ?

The warnings :
Warning (org-roam): Skipping unreadable file while building cache: /Users/lss/Documents/Org/notes/2020-05-28.org

Again all files are concerned whether they've been modified or not. New or older.

**Comment by myshevchuk** [comment]
I'm on Emacs 27.1 mac port since the middle of August. I update all my Emacs packages every day or two and never had this issue. Emacs-plus 27.1 is also rock solid, courtesy of @d12frosted. Emacs 28 perhaps less so. But that doesn't matter because it has nothing to do with Org-mode (or Org-roam).

Look for what could cause the reason of this error. Maybe you moved your files or accidentally changed the ownership... Also, have you cleared Org-roam cache (org-roam.db) and rebuilt it after the upgrade? It often helps.

**Comment by blockynight** [comment]
Hi @lsiksous 
I had similar warnings today for all my files in `org-roam-directory`. I found and fixed the problem by looking at the backtrace of running (with `toggle-debug-on-error` on) something like:
`(org-roam--with-temp-buffer "path to an org-roam note file" (org-roam-db--insert-links))`.

**Comment by lsiksous** [comment]
Thanks @blockynight ! I followed your advice and found out it was my version of org-ref that was causing the problem.

**Comment by cauchycai** [comment]
Still an issue.

**Comment by spacekitteh** [comment]
Yep, just started happening for me too.

**Comment by spacekitteh** [comment]
Ok, actually, it seems to happen because of a failure to initialise a certain buggy minor mode each time it opens a new temp buffer.
