### ISSUE TITLE
Acronym and reference links in header

### ISSUE THREAD

**Issue by junwei-wang** [org-roam/org-roam#1335]
### Brief Abstract

To add acronym and reference links in header.

### Long Description

A lot of users of org-roam use it to maintain personal wiki. 
For such a usage, many entities are professional knowledge which has a acronym name.
`ROAM_ALIAS` could be used to store such a acronym, but it would be even nicer if we have a special header item reserved for acryonym.

Additionally, many knowledge can be referred to wikipedia or some profession websites, if there exists a header item for external reference such as wikipedia, it would be nicer.

### Please check the following:

AFAK,

- [x] No similar feature requests

**Comment by randomwangran** [comment]
Hi Junwei:

Org-roam was designed to suit the small-files principle instead of
building on headlines using big Org files. This has been discussed
extensively in the community, e.g. Emacs conference 2020 and
r/emacs. I personally use a combination of them. Acronyms within a
narrow topic are stored in few files.

Speaking a special headline item, I think you are referring to
`:PROPERTIES:`. In the following example, a headline with a special
`:PROPERTIES:` is attached to this headline.

User could query its value from function `org-property-values`. This
can be further extended to user specific interactive function, e.g.
open with external browser.

    * encry
     :PROPERTIES:
     :ID:       42
     :Status:   7
     :ENCRY:    https://en.wikipedia.org/wiki/Encryption
     :END:

      (car (org-property-values "Status"))
    → "7"
    
      (car (org-property-values "ENCRY"))
    → "https://en.wikipedia.org/wiki/Encryption"

**Comment by junwei-wang** [comment]
I think I made a mistake. What I suggest is to store acronym and external links to headers or properties.

**Comment by jethrokuan** [comment]
> ROAM_ALIAS could be used to store such a acronym, but it would be even nicer if we have a special header item reserved for acryonym.

Why would it be nicer? If you can put forth a convincing argument I'd think about it, but otherwise it's just additional an code path to maintain.
