### ISSUE TITLE
Add selectrum to org-roam-completion-system

### ISSUE THREAD

**Issue by mohkale** [org-roam/org-roam#1363]
### Brief Abstract
[Selectrum](https://github.com/raxod502/selectrum) is a new completion-framework.

### Long Description
`org-roam-completion-system` has a few completion frameworks supported out of the box, but as of yet selectrum isn't there :/.

### Please check the following:

- [X] No similar feature requests

**Comment by jethrokuan** [comment]
If you're using selectrum, then you can leave `org-roam-completion-system` as `'default`, since the default is to just use the `completing-read` API.

Org-roam currently just uses `completing-read`, but I can foresee many scenarios where a more sophisticated completion system can be useful. These are not high up on the priority list, but when they do get implemented, they will likely be made available as separate packages.

**Comment by oatmealm** [comment]
Does it actually work? I've enabled `selectrum` (in doom) changed `org-roam-completion-system` but I'm getting no candidates.... while switching back to `ivy` it does work.

**Comment by jethrokuan** [comment]
Enable selectrum, and leave `org-roam-completion-system` as is.
