### ISSUE TITLE
Daily capture ignores trailing line breaks in template

### ISSUE THREAD

**Issue by seriousbusinessuser** [org-roam/org-roam#1368]
### Description
`org-roam-dailies-capture-today` ignores trailing line breaks in the capture template.

#### Steps to Reproduce
1. Execute this code(you can change `file-name` option):
```
  (setq
   org-roam-dailies-capture-templates
   '(("d" "default" entry
      #'org-roam-capture--get-point
      "* %?"
      :file-name "daily/%<%Y-%m-%d>"
      :head "#+TITLE: %<%Y-%m-%d>\n#+STARTUP: overview\n\n")))

```
2. If you already have daily file for today then move/delete it. 
3. Run `org-roam-dailies-capture-today` command.
4. Enter "Test".
5. Press `C-c C-c`.

#### Expected Results

```
#+TITLE: 2021-01-02
#+STARTUP: overview

* Test
```

#### Actual Results

```
#+TITLE: 2021-01-02
#+STARTUP: overview
* Test
```

### Environment
- Emacs: GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.22, cairo version 1.17.3)
 of 2020-08-28
- Framework: Spacemacs
- Org: Org mode version 9.4.4
- Org-roam: 1.2.3

**Comment by jethrokuan** [comment]
This has to do with how the `entry` type is handled within `org-roam-capture`.

https://github.com/org-roam/org-roam/blob/7352a5a0f664b023ad13d300b8880ebd48bb27e2/org-roam-capture.el#L443

Not a fan of how this is handled atm (cc @zaeph )

**Comment by jethrokuan** [comment]
Actually this is because `org-capture`'s template expansion trims additional new lines, and I think it's more trouble fixing this (by emulating org-capture's template expansion) than it is worth, so I won't be attempting to fix it. If anyone can find a clean solution, I'm open to PRs.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
I know nothing about the technical details (nor Lisp). But I also run into that problem.

From a users perspective I see this as a heavy bug. You can configure nearly everything with OrgRoam but it is not able to handle newlines in capture templates.

I vote for ReOpen because the bug is still there.

**Comment by wakatara** [comment]
I just came looking for a solution to this one as well since my newlines in capture templates )several of them quite long) were being ignored. I vote for re-opening this one as well. It is quite problematic since you need to manually add in newlines once you've created a new file and is an extreme point of friction in terms of effortless and quick notetaking or entry.

**Comment by luk3rr** [comment]
You can try using ":empty-lines". I use it this way:
```lisp
 (setq org-roam-dailies-capture-templates
        '(("d" "Diary" entry "* %<%H:%M> %?"
           :empty-lines 1
           :target (file+head "~/Org/Diary/%<%Y-%m-%d>.org"
                              "#+title: %<%A, %Y-%m-%d>\n------\n")
           :unnarrowed t
           :empty-lines 1))
```
