### ISSUE TITLE
org-roam-protocol-open-ref always captures, even if ref-link already exists

### ISSUE THREAD

**Issue by rakoenig** [org-roam/org-roam#1371]
https://github.com/org-roam/org-roam/blob/15d864a500d90c9dc2e16d888e93343528ec3941/org-roam-protocol.el#L51

According to this (and the documentation in the user manual) I assume if roam-ref protocol is called for a link that exists already then roam-ref protocol should open that note instead of capturing a new one (which then would lead to duplicate ref warnings).

I'm not yet an experienced Emacs lisp programmer, looking around I see a function `org-roam--find-ref` in "org-roam.el" which is never called anywhere, but it looks like this should be the function to see if a ref-link already exists.

**Comment by jethrokuan** [comment]
> According to this (and the documentation in the user manual) I assume if roam-ref protocol is called for a link that exists already then roam-ref protocol should open that note instead of capturing a new one (which then would lead to duplicate ref warnings).

Yes, that's correct, and it's how it works for me. There are a lot of parts that need to be correct before you get the expected behaviour, so let's try to make sure everything's in place:

1. What ref template are you using? Would be good if you can share your value of `org-roam-capture-ref-templates`.
2. What does your bookmarklet look like?

> I'm not yet an experienced Emacs lisp programmer, looking around I see a function org-roam--find-ref in "org-roam.el" which is never called anywhere, but it looks like this should be the function to see if a ref-link already exists.

That looks like dead code, which can be safely removed.

**Comment by rakoenig** [comment]
`org-oram-capture-ref-templates looks like this:
`
```
(setq org-roam-capture-ref-templates
   '(("r" "ref" plain
	#'org-roam--capture-get-point
	"%?"
        :file-name "ref/%<%Y%m%d%H%M%S>-${slug}"
        :head "#+title: ${title}\n#+roam_key: ${ref}\n\n%i"
        :unnarrowed t)
     ))

```
The bookmarklet looks like this:

`javascript:location.href =     'org-protocol://roam-ref?template=r&ref='     + encodeURIComponent(location.href)     + '&title='     + encodeURIComponent(document.title)     + '&body='     + encodeURIComponent(window.getSelection())
`

So everything according to the documentation. When you write _"Yes, that's correct, and it's how it works for me"_ does that mean, that on your system it really opens the note if the ref exists already? I'm really not seeing any code in `org-roam-protocol-open-ref` that would do this.

**Comment by jethrokuan** [comment]
They do look correct to me. There could be a bug with `encodeURIComponent`, Emacs encoding/decoding of strange URLs, but if it doesn't work on say `https://github.com`, then something else is going on.

> When you write "Yes, that's correct, and it's how it works for me" does that mean, that on your system it really opens the note if the ref exists already?

Yes, exactly.

> I'm really not seeing any code in org-roam-protocol-open-ref that would do this.

That's because the handling is really done within `org-roam-capture--get-point`.

https://github.com/org-roam/org-roam/blob/7352a5a0f664b023ad13d300b8880ebd48bb27e2/org-roam-capture.el#L522-L527

**Comment by rakoenig** [comment]
Ok, I start to understand how its supposed to work. So I played around within the scratch window and this happened:

```
(org-roam--get-ref-path-completions)
(("//github.com/org-roam/org-roam" :path "/home/rainer/Dropbox/org-roam/ref/20210110114438-org_roam_org_roam_rudimentary_roam_replica_with_org_mode.org" :type "website" :ref "//github.com/org-roam/org-roam")...
```

So it looks like `org-roam--get-ref-path-completions` returns the refs without a leading "https:" while I guess that `ref` in `org-roam-capture--info` still has the whole ref URI including the prococol part. 

Just two more attempts in the scratch buffer:

```
(cdr (assoc "//github.com/org-roam/org-roam" (org-roam--get-ref-path-completions)))
(:path "/home/rainer/Dropbox/org-roam/ref/20210110114438-org_roam_org_roam_rudimentary_roam_replica_with_org_mode.org" :type "website" :ref "//github.com/org-roam/org-roam")
```
versus

```
(cdr (assoc "https://github.com/org-roam/org-roam" (org-roam--get-ref-path-completions)))
nil

```

Looks like the refs are stored without the protocol specs in the database (that I cleared and rebuild):

```
sqlite> select * from refs;
"//github.com/emacs-helm/helm/wiki#general-concept"|"/home/rainer/Dropbox/org-roam/home_emacs_helm_helm_wiki.org"|"website" ...
```

**Comment by jethrokuan** [comment]
Right, actually it looks like it has worked for me all along because the generated file path for a given URL is the same for me, and `org-roam-capture--new-file` wasn't catching this. Creating a PR that should fix this.

**Comment by znewman01** [comment]
Hey, thanks for your work on this project!

Since this change I get the "Attempted to recreate existing file" warning message every time on `org-roam-dailies-find-today`. I've checked that my daily file is in the db:

```bash
$ sqlite3 ~/.emacs.d/.local/etc/org-roam.db \
       "select count(*) from files where file like \"%roam/daily/$(date -Idate).org%\";"
1
```

My `org-roam-capture-ref-templates` is the default:

```emacs-lisp
(("r" "ref" plain #'org-roam-capture--get-point "%?" :file-name "${slug}" :head "#+title: ${title}\n#+roam_key: ${ref}" :unnarrowed t))
```

(Happy to open a new issue if that's appropriate, and I could totally be doing something wrong.)

**Comment by cmrfrd** [comment]
I've experienced the "Attempted to recreate existing file before" when I used org-protocol on two different websites that had the same title. As of `v1.2.3` [it looks like](https://github.com/org-roam/org-roam/blob/cc01cf346e2d832f78694320947e0788c92f49b9/org-roam-capture.el#L571) when you use `:file-name "${slug}"` in your `org-roam-capture-ref-templates`, the filename that gets produced is based on the title of the webpage.

I found that using a "file friendly" version of the url has a less chance of colliding with another filename whose title was the same.

Ex:
```
https://gihub.com -> "https_github_com"
``` 

So instead of using `${slug}` I put in my ref templates variable

```
(setq org-roam-capture-ref-templates
   '(("r" "ref" plain
	#'org-roam--capture-get-point
	"%?"
        :file-name "%(org-roam--title-to-slug \"${ref}\")"
        :head "#+title: ${title}\n#+roam_key: ${ref}\n\n%i"
        :unnarrowed t)
     ))
```

Since `org-roam` is using `org-capture` under the hood you can leverage [Template Expansions](https://orgmode.org/manual/Template-expansion.html). I recommend this over the traditional `${slug}`

**Comment by znewman01** [comment]
Oh, good tip! I believe #1387 addresses the issue from my previous comment.
