### ISSUE TITLE
docs: explain and list all expansion variables

### ISSUE THREAD

**Issue by jwhendy** [org-roam/org-roam#1399]
I'm just getting started with org-roam. It looks awesome and I'm quite excited, though [the docs](https://www.orgroam.com/manual.html#Org_002droam-Template-Expansion) aren't necessarily as comprehensive as I'd like (my opinion).

For an example:

The first introduction to `${slug}` is in the template walkthrough, with a reference to `${title}` right after. In the section on template explansion that follows:

> In org-roam templates, the `${var}` syntax allows for the expansion of variables, stored in org-roam-capture--info

Only `${title}` appears explicitly mentioned, but there are clearly more, as we have `${slug}` in the capture template walkthrough and I stumbled on `${ref}` in [an issue](https://github.com/org-roam/org-roam/issues/635#issuecomment-629601638). From usage, it appears that `${slug}==${title}` but I'm guessing I'm wrong about that... Are there more of these and could they be listed with explanations?

I'm also wondering if there's other documentation? The user manual is nice, but almost seems less technical/detailed than I'd expect? I saw a link to a different [doc site](https://org-roam.readthedocs.io/en/master) and wondered if there's a more detailed spec I haven't found yet.

I'd be happy to take a stab at a PR if someone could point me in the right direction and agrees this would be a helpful addition. Many thanks!

**Comment by jwhendy** [comment]
Same suggestion for template options. I was just wondering about inserting a new headline vs a file. In my previous capture templates I could do `file+headline` for the path selector. While I still haven't figured this out for `org-roam`, if I do I'll want to look at `:prepend` as an option.

The [template section](https://www.orgroam.com/manual.html#Template-Walkthrough) references `:file-name`, `:head`, `:unnarrowed`, and that I "may want to learn about `:immediate-finish`, but I'm not sure where to do that.

That option along with `:unnarrowed` are in the OG [org capture docs](https://orgmode.org/manual/Template-elements.html#Template-elements), but in the lead up to learning about capture we have:

> For these reasons, Org-roam capture templates are not compatible with regular org-capture. 

Without trial and error, I'm not sure what I have at my disposal from org vs. what is incompatible. A table that represents the Venn diagram I imagine of purely org, purely org-roam, and the intersection of the two would be fantastic.

**Comment by jethrokuan** [comment]
I agree that the docs are sparse here. As context, a lot of the Org-roam capture templating is just hacks built on top of Org-capture. The reasons docs are sparse are that I don't expect much deviation from the regular templates, and I don't guarantee that advanced template usage will work. Regardless, I'll try my best to answer your questions here.

> From usage, it appears that ${slug}==${title} but I'm guessing I'm wrong about that... Are there more of these and could they be listed with explanations?

These `${var}` expansions exist only because `org-capture` doesn't support injecting variable values in the templates. We need this functionality to have a single capture template produce different results. The ones that exist are:

1. `title`: The entered title in the minibuffer completion
2. `slug`: The title, converted into a friendly name to be used as the filename: See `org-roam-title-to-slug-function`.
3. `ref`: If capturing using `org-roam-protocol`, this is the `roam-ref` key.

Org-roam reads `org-roam-capture--info`, and fills in these variables. If it doesn't exist in that variable, the user is prompted to fill it in.

> In my previous capture templates I could do file+headline for the path selector. While I still haven't figured this out for org-roam, if I do I'll want to look at :prepend as an option.

Right now, Org-roam's capture template doesn't support that. It only officially supports `'plain`, with `org-roam-capture--get-point`, actually, because a lot of work is done in `org-roam-capture--get-point`, including file creation and header template injection. Other than that, most of `org-capture's` template functionality should work.

Building capture functionality on top of Org-capture was easier earlier, the monkey patching makes it difficult to figure out what will work and what won't.  What eventually needs to happen is a complete rewrite of the capturing system, so we can cleanly support key functionalities of Org-roam, including variable expansion and nested captures, without all the monkey patching.

**Comment by jwhendy** [comment]
Thanks for the quick clarification, and I think that gives me what I'd like for now! Would you like any doc tweaks, like inserting that list of `${var}`s, or a list of what `:foo` options are available?

After I posted I saw a comment in another issue directing someone toward code as the the primary documentation. I get that, though despite being a long time org user, I've never gotten into elisp. What about having links from a concept when it's introduced in the docs to the corresponding `*.el` file/line number? That could effort into docs that might change (as I infer will happen if/when you rewrite) while also leaving some breadcrumbs for us noobs :)
