### ISSUE TITLE
Support namespaces like roam

### ISSUE THREAD

**Issue by faldor20** [org-roam/org-roam#1417]
### Brief Abstract
Roam supports having namespaces so that [[org-roam/docs]] can be different to [[Emacs/docs]] but both can show as "docs" when linked to. It's very hard to do notes for projects without being able to have namespaces like this

**Comment by nobiot** [comment]
I’d just use a sub folder for this purpose. Any reason why that might not be a good fit for your project notes?

**Comment by dangom** [comment]
@nobiot if you have the time, could you expand on your solution? Would love to hear about it. Thank you.

**Comment by gcr** [comment]
@dangom if i understand it, the idea is to have your zettels in two folders, call them (for example) `roam/` and `dailies/`. Then you can simply link to the files by their title without worrying about which folder they live in.

Incidentally, org-roam also supports `/` in note titles straight out of the box, so you don't even need to keep these notes in separate folders.

**Comment by faldor20** [comment]
Yes @nobiot I was not aware that org-roam links respected folder hierarchy. If so that would be super cool and handy... It would be really handy to be able to save many same named notes in folders and be able to reference them just by name within that folder but need a path qualifier when outside. 
For example:
Emacs/docs/shortcuts
Vscode/docs/shortcuts
If I am i am writing in "Emacs/docs/overview" and I type "shortcuts" I can link to either:
"Shortcuts"
Or "Vscode/docs/shortcuts"
You could allso do this with just named files like dendron for Vscode does. It aims to solve this exact problem.

I love the roam linking style but I agree with the creator of dendron. In that; for projects you will have many duplicate notes such as documentation and such. And being able to differentiate them and link to them easily when within a specific project is needed.

**Comment by faldor20** [comment]
Or just being able to collapse a link from "Emacs/docs" to "docs" or "e/docs" would achieve 80% of the utility. And of course showing both as completions when typing "docs"

**Comment by d12frosted** [comment]
> I was not aware that org-roam links respected folder hierarchy

I really-really suggest using `id` type links as opposed to path links. They completely ignore hierarchy and you can safely move your files in whatever what you feel it. 

I actually also have notes sharing the same name and want to reference them from different places. So in your example:

```
Emacs/docs/shortcuts
Vscode/docs/shortcuts
```

Instead of using `[[|]]` style completion, I bind `org-roam-insert` to some convenient key combination (in my case `M-m n i`) and I simply type `shortcuts` and completion system shows me something like:

```
(Emacs, docs) shortcuts
(Vscode, docs) shortcuts
```

*side note*: you could type `docs` in completion buffer and both would popup as well.

And once I select what I need, the following thing is inserted to the buffer:

```
[[id:cfd7e6f8-ec70-4563-8301-7f5918761009][shortcuts]]
```

Where `cfd7e6f8-ec70-4563-8301-7f5918761009` is ID of the selected note. Now the valid question - what the hell is `(Emacs, docs)` thing in the completion buffer? Tags :D And `org-roam` supports tags extraction from various place - from properties of the node (note), e.g. `#+ROAM_TAGS` and from directories. For your example to work you need to set the value of `org-roam-tag-sources`:

```emacs-lisp
(setq org-roam-tag-sources '(prop all-directories))
```

Please refer to description of that variable for more information: `C-h v org-roam-tag-sources <ret>`. 

P. S. I understand that strictly speaking it's not the same flow as in roam research (at least from how you describe it), but maybe what I described fits your needs.

**Comment by nobiot** [comment]
I would separate three different things:
1. Save notes in sub-directories
2. Completion-at-point with Company
3. Completion in minibuffer

For 1, you can just save your files in a sub-folder. You can use org-roam's templating system to differentiate where the note should be saved (the `:file-nanme` property can take relative path)

For 2, this is probably what @faldor20 is mostly concerned with. Depending on whether or not you have titles to your notes, it would like this:

   ![2021-02-04T080300_subfolder](https://user-images.githubusercontent.com/12507865/106857369-4312ed80-66c0-11eb-8c7a-835d8690c265.gif)

For 3, you can configure Org-roam to treat sub-directories as a tag, which appears in completion in minibuffer

I have "personal" and "work" sub-directories within my org-roam-directory.

Here is a screen grab of my minibuffer. Note that second one has a title, and that's the reason it does not show "/". The rest are missing titles, so they show filenames followed by their directory and a "/". 

What's in the brakets "()" are their tags; I set Org-roam to use the first sub-directory as a tag.

   ![image](https://user-images.githubusercontent.com/12507865/106857963-38a52380-66c1-11eb-824e-21695a07e986.png)

I suggest you look at the documentation of variable `org-roam-tag-sources`, and play with it (see either `all-directories`, `last-directory`, and `first-directory` for example.  I use `first-directory`. 

@dangom , I don't use Company very often; I mostly rely on minibuffer.

**Comment by nobiot** [comment]
@d12frosted we were writing at the sam time I guess ;)

**Comment by d12frosted** [comment]
@nobiot haha, indeed. But I love how structured and visalised your answers are 💯 

Can you please share your template for notes? Do you create multiple templates per each folder? 

I approach this in the following manner:

```emacs-lisp
(setq org-roam-capture-templates
        '(("d" "default" plain
           #'org-roam-capture--get-point
           "%?"
           :file-name "%(+org-notes-subdir)/%<%Y%m%d%H%M%S>-${slug}"
           :head "#+TITLE: ${title}\n#+TIME-STAMP: <>\n\n"
           :unnarrowed t)))

(defun +org-notes-subdir ()
  "Select notes subdirectory."
  (interactive)
  (let ((dirs (cons "."
                    (seq-map
                     (lambda (p)
                       (string-remove-prefix org-roam-directory p))
                     (+file-subdirs org-roam-directory nil t)))))
    (completing-read "Subdir: " dirs nil t)))

(defun +file-subdirs (directory &optional filep rec)
  "Return subdirs or files of DIRECTORY according to FILEP.

If REC is non-nil then do recursive search."
  (let ((res
         (seq-remove
          (lambda (file)
            (or (string-match "\\`\\."
                              (file-name-nondirectory file))
                (string-match "\\`#.*#\\'"
                              (file-name-nondirectory file))
                (string-match "~\\'"
                              (file-name-nondirectory file))
                (if filep
                    (file-directory-p file)
                  (not (file-directory-p file)))))
          (directory-files directory t))))
    (if rec
        (+seq-flatten
         (seq-map (lambda (p) (cons p (+file-subdirs p)))
                  res))
      res)))

(defun +seq-flatten (list-of-lists)
  "Flatten LIST-OF-LISTS."
  (apply #'append list-of-lists))
```

So basically, I have one capture template which asks me in which folder to save captured note. 

![image](https://user-images.githubusercontent.com/6507913/106860412-07caeb80-66cd-11eb-9b88-1d1c095057eb.png)

P. S. I believe `+file-subdirs` can be replaced with something simpler.

**Comment by faldor20** [comment]
Wow @nobiot Thanks for the great answer... honestly i can't really fault that. That's 90% of what i wanted sorted right there. 👍 
@d12frosted That script looks very handy. Might give it a go.
I'll close the issue now if the rest of you are done.

**Comment by nobiot** [comment]
@faldor20 , happy for you to close this.

@d12frosted , I only started using Org-roam for work for real this year, and I am new to org-capture in general. I struggled to understand the `%(EXP)` in the manual -- now you showed me how I should interpret it and use it haha 😅

I have only one `org-roam-template`. Here is what I do -- works for now, but I'll probably keep tweaking it for the next couple of months.

At the moment, my private notes are all in markdown (with my Md-roam) -- this is so that I have a better editing experience in writing notes on my iPad (I use iA Writer). I have rarely use the one `org-roam-capture` template I have for my personal markdown notes. I normally capture notes on my iPad, and manually move them to evergreen (either on my iPad, or Emacs on my PC).

For work, I use org notes, but to create new ones, I use my custom version of [`usls.el` by Prot ](https://gitlab.com/protesilaos/usls). This is purely borne out of my curiosity (I'm a fan of his work); I might go back to `org-roam-capture` template now that I know how I can use `completing-read` 😎

**Comment by nobiot** [comment]
@dangom , if you have more questions, happy to continue here (even after it closed), or we can take the discussion in Org-roam's Discourse forum, if you post a question.

**Comment by nobiot** [comment]
@gcr , 

> org-roam also supports / in note titles straight out of the box

I didn't know this -- it's good to know. My custom way does not do this (it tries to create a subfolder that I don't want). I'd love to inspect the code how Org-roam does it (and my custom one with `usls.el` doesn't). Thanks!

**Comment by d12frosted** [comment]
@nobiot capturing is complex 🤔 I am still learning it. Recently I realised that you can also use functions for capture target and template, which gives so much power. If you are interested, I can share a configuration I made for captuing meeting notes.

Intersting flow. In my case it's simpler as I using org mode for a long time (only recently started to do anything not-simple), so my notes base is not splitted. Yes, I had to migrate from my old org mode based system to org-roam, but it was semi-automatic, as with org you can write migration scripts easily :) From markdown I bet it can be also automated using pandoc and a bunch of haskell (cause pandoc is in haskell) or elisp scripts. Would be nice to hear about your migration once it's done :) In case you are planning to, ofc.

I never heard about usls.el, so thanks for sharing. I will take a look.

**Comment by nobiot** [comment]
@d12frosted, I think I’ll stay with markdown for my personal notes. I’ll see how far I can get with it :)
