### ISSUE TITLE
Roam needs to be restarted after creating new pages

### ISSUE THREAD

**Issue by pangloss** [org-roam/org-roam#1427]
### Description

I just installed this today and while building up the database by bringing in existing notes, I noticed that the backlinks page would stop updating until I cycled org-roam-mode off/on and switched notes. 

#### Steps to Reproduce

1. go to an existing page
2. Open backlinks pane
2. make a link to a new page
3. follow it
4. Press C-c C-c in the capture window and save the file.
5. switch notes -- it is dead

#### Backtrace
none

### Environment

Copy info below this line into issue:
- Emacs: GNU Emacs 27.1 (build 1, x86_64-apple-darwin19.5.0, Carbon Version 162 AppKit 1894.5)
 of 2020-11-14
- Framework: Spacemacs
- Org: Org mode version 9.4 (9.4-17-g9a6689-elpaplus @ /Users/dw/.emacs.d/elpa/27.1/develop/org-plus-contrib-20201005/)
- Org-roam: 1.2.3

**Comment by nobiot** [comment]
Do you wait for 2 seconds after saving the new note for the DB update to occur?
You should see a message in the echo area for org-roam saying something like "(org-roam) Updated: ..."

**Comment by pangloss** [comment]
Yes I see that message normally, but after visiting a newly created note file I won't see it again until I restart roam as described, no matter which note I subsequently navigate to.

**Comment by pangloss** [comment]
I think this may only happen if the backlinks pane is open.

**Comment by nobiot** [comment]
I don't use Spacemacs, and I don't have issues with new notes.
But I cannot be sure if I can or cannot reproduce your problems.
I don't understand how you really do these steps, 

2. Open backlinks pane
3. make a link to a new page
4. follow it
5. Press C-c C-c in the capture window and save the file.

How do you "make a link to a new page" (what command, or type?)
How do you follow it (mouse click, or a command?)
And... why do you need to press C-c  C-c -- does it do anything?

In any case... One suggestion I can make is that you ensure Spacemacs is not interfering (I don't use it, and since mine works, I suspect it is somehow interfering).
You can use Emacs with no configuration, and see if you can reproduce the problem yourself.
https://org-roam.discourse.group/t/beginners-guide-to-troubleshooting-emacs-problems-an-org-roam-edition/224

**Comment by pangloss** [comment]
Although this issue consistently happened when I was first creating my notes (even after restarting Emacs), when I try now I also can't reproduce the problem, so I'm going to close it.

BTW, to make the link I was just typing `[[roam:something]]`. When I move my cursor over the link that text becomes and press `Enter`, it brings me into a capture window that requires me to press C-c C-c to actually create the file. Perhaps that is spacemacs only.

Closing the issue, thanks.
