### ISSUE TITLE
org-parse-time-string: Not an Org time string: diary

### ISSUE THREAD

**Issue by Jousimies** [org-roam/org-roam#1585]
### Description
Press Ctrl-c Ctrl-s to add a schedule to a TODO item, echo the error as org-parse-time-string: Not an Org time string: diary.
#### Steps to Reproduce
1. open a note (A.org) wiht `org-roam-node-find`
2. create a TODO item in A.org
3. press `C-c C-s` to add a schedule.
then the error appeared.

### Environment

- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/commithashhere

**Comment by Wetlize** [comment]
I've tried to reproduce your issue and everything works as expected. It's probably something broken on your side and since you didn't fill the `Backtrace` and `Environment` headings it's really hard to tell what's going there.

I think this can be closed, since the issue isn't related to `org-roam`, but something weird on the user side.

**Comment by Jousimies** [comment]
I did some test. 

if I setq org-roam-directory to another path, the problem appeared.

If I do not set this variables, everything ok.

**Comment by Jousimies** [comment]
```lisp
(add-to-list 'load-path (expand-file-name "packages/org-roam" user-emacs-directory))
(add-to-list 'load-path (expand-file-name "packages/dash" user-emacs-directory))
(add-to-list 'load-path (expand-file-name "packages/f" user-emacs-directory))
(add-to-list 'load-path (expand-file-name "packages/s" user-emacs-directory))
(add-to-list 'load-path (expand-file-name "packages/magit/lisp" user-emacs-directory))
(add-to-list 'load-path (expand-file-name "packages/emacsql" user-emacs-directory))

(require 'org-roam)
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(org-roam-directory "/home/jousimies/L.Galaxy/roam"))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
```

a minimal config to reproduce this problem, with emacs version: GNU Emacs 27.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.27, cairo version 1.17.4)

step:
1. `org-roam-node-find` create a org-roam note, such as test.org
2. create an TODO item, such as "* TODO this is a test"
3. put the cursor on the line of TODO item, and press `C-c C-s` to create schedule.
4. the minibuffer will echo "org-parse-time-string: Not an Org time string: diary"

**Comment by jethrokuan** [comment]
I can't seem to reproduce, things are fine with your minimal config.

![image](https://user-images.githubusercontent.com/1667473/126047817-ced57bde-cb16-463f-8ce0-23e2d47586c9.png)

Maybe you can launch emacs with `--debug-init` and get the backtrace.

**Comment by jcronenberg** [comment]
For me this error appears when I set org-roam-dailies-directory. For some reason I need to set the roam directory to an empty string or else it searches in "daily/daily/" (which is also weird behaviour).
When the directory is **incorrect** (so set to "daily/") I can use org-schedule.
If it is **correct** (set to "") org-schedule doesn't work anymore.

**Comment by Jousimies** [comment]
This problem appeared when set org-roan-directory to another path, not the default one.

**Comment by jcronenberg** [comment]
Yes, that's the case for me too, sorry should have specified that. I just wanted to report my findings that it (at least for me) also has to do with the org-roam-dailies-directory.

**Comment by jcronenberg** [comment]
It appears to be fixed for me. My problem was that I had "daily/%<%Y-%m-%d>.org" for the filepath in the dailies capture template. Changing it to just "%<%Y-%m-%d>.org" has fixed it. That also explains the weird behaviour I had. I don't know if this is relevant to this issue, but maybe it helps someone :)

**Comment by mbafford** [comment]
Confirming this issue comes down to the function `org-roam-dailies-calendar--file-to-date`:

```
(defun org-roam-dailies-calendar--file-to-date (&optional file)
  "Convert FILE to date.
Return (MONTH DAY YEAR)."
  (let ((file (or file
                  (buffer-base-buffer (buffer-file-name)))))
    (cl-destructuring-bind (_ _ _ d m y _ _ _)
        (org-parse-time-string
         (file-name-sans-extension
          (file-name-nondirectory file)))
      (list m d y))))
```

The call to `org-parse-time-string` will raise an error if one of the files in the default "dailies" folder is not named conforming to the expected format for an org-mode time string.

So files will fail if they are named basically anything other than `YYYY-MM-DD`, I believe.

I know almost nothing about elisp at this point, so I solved this by setting my dailies folder to something with no files in it:

```
(setq org-roam-dailies-directory "~/org/org-roam-dailies-empty-dir/")
```

The issue manifests as various functions which invoke the calendar (`org-capture`, `org-schedule`, others) failing with an error like:

``` "Not an Org time string: %s"```

Where `%s` ended up being semi-random from the various file names in your notes, in my experience.

I don't know Elisp enough to update the code to handle this error case, but it seems like an easy fix:

1. ignore the files that don't pass the `org-parse-time-string` parsing
2. don't set a default value for `org-roam-dailies-directory` and have the functionality disabled / error out *only* if explicitly invoked rather than implicitly invoked through opening the calendar

**Comment by Jousimies** [comment]
@mbafford Thank you! 
I set org-roam-dailies-directory to an empty folder, solved this problem.

@jethrokuan Can it been fixed officially?

**Comment by mbafford** [comment]
Confirmed resolved for me with https://github.com/org-roam/org-roam/commit/2fe233ffa0c590678807cbc344accbf8e8861de0 - thanks!
