### ISSUE TITLE
Org-roam-mode "silently" broke emacs daemon

### ISSUE THREAD

**Issue by lcvass** [org-roam/org-roam#1644]
Using Emacs from NixOS-unstable, and Emacs daemon as a systemd service through the "services.emacs" NixOS option.

I had the now-removed org-roam-mode enabled in my configuration. After updating org-roam to V2 yesterday, from MELPA, the daemon would hang out while attempting to start. Logs did mention the migration message but not an error.

The solution was easy as I could still start an independant Emacs instance and see the migration warning buffer. Removing org-roam-mode fixed it. 

The underlying cause may not even be worth fixing but I guess seeing an error on the logs would've been nice.

**Comment by jdreaver** [comment]
I saw this exact same thing on Arch Linux.

```
thinkpad% emacs --version
GNU Emacs 28.0.50
```

I just updated org-roam to v2, and I couldn't start `emacsclient`. Also, my `*scratch*` buffer was read only for some reason. After removing `org-roam` from my config, `emacsclient` works again and my scratch buffer is back to normal.

**Comment by zamlz** [comment]
Oh is that what happened, because I noticed this too. temporarily disabled daemon mode for now lol

**Comment by jethrokuan** [comment]
There's not much I can do about this... The old v1 config will error out if the v2 package is loaded. I'm not sure if it's possible to print anything to the systemd logs either.

**Comment by zamlz** [comment]
Hmm okay I  think my daemon error is different because the migration was successful and i don't see that message anymore because I added the variable as well.

**Comment by lcvass** [comment]
@zamlz did you remove `org-roam-mode` from your emacs configuration? That is all I had to do.

**Comment by jethrokuan** [comment]
> perhaps you could reimplement org-roam-mode to just emit a warning? 

It serves a different purpose now, so no-can-do.

**Comment by jdreaver** [comment]
@jethrokuan to be clear:

* When running Emacs normally (not via `emacsclient`), I saw the warning and added the ack line to my config.
* Running Emacs normally again worked fine.
* Running Emacs via `emacsclient` breaks silently. No error messages are printed. It just hangs on startup.
* Removing `org-roam` from my config fixed `emacsclient`.

Is there something in `org-roam` v2 that expects an active frame on startup?

**Comment by jethrokuan** [comment]
> Is there something in org-roam v2 that expects an active frame on startup?

Nope, `org-roam` loads fine for me in `emacsclient` without any hanging. There should be no difference between launching an `emacsclient` instance and `emacs` instance... what does your config look like?

**Comment by adql** [comment]
I had `(add-hook 'after-init-hook 'org-roam-mode)` somewhere in my configuration remaining from `v1` which caused the same problem (which I hadn't really noticed because I use `(server-start)` instead of daemon). I remember seeing _somewhere_ the instruction to add this, but I couldn't find it again. I believe it was the way to go in `v1`, wasn't it?

Anyway, removing this solves the problem because indeed `org-roam-mode` should not be started as a global mode anymore. But it's possible that other people have this line somewhere forgotten in their config, so it may be worth to mention this under [`org-roam-mode` is no longer a global minor mode](https://github.com/org-roam/org-roam/wiki/Hitchhiker's-Rough-Guide-to-Org-roam-V2#org-roam-mode-is-no-longer-a-global-minor-mode) in the transition wiki page.

**Comment by zamlz** [comment]
Oh I removed this because of another issue i opened as well. This could fix
it, I'll have ot turn on the daemon again and see if it works!

**Comment by lcvass** [comment]
Closing this since most people have likely already migrated.

**Comment by c02y** [comment]
Is this bug fixed?

Once I enable org-roam, emacsclient won't start since there is no server from `lsof -c emacs | rg server`

I'm using spacemacs, I've never used org-roam BTW.

**Comment by jethrokuan** [comment]
@c02y there is no bug, launch emacs with `emacs --debug-init` to find out why your client isn't starting.

**Comment by c02y** [comment]
@jethrokuan 

`emacs --debug-init` starts fine, execpt one line in `imenu-unavailable-error: Opening directory: No such file or directory, /home/user/org-roam` in **\*Messages\*** buffer

so thank you, I found the bug, if `~/org-roam` doesn't exist, emacsclient won't start, since no server from `lsof -c emacs | rg server` after running emacs daemon or systemd service, once I `mkdir ~/org-roam`, it works OK.

Is it a bug? I believe it is. 😅

**Comment by jethrokuan** [comment]
It's a bug in your config then, because `org-roam` doesn't mandate that the directory exists, it's some interaction you have with `imenu` (is something launching imenu on emacs startup?) that's causing your Emacs to fail to load completely.

**Comment by c02y** [comment]
I just search the repo page and found https://github.com/org-roam/org-roam/blob/master/doc/org-roam.org#setting-up-org-roam part, sorry I didn't read the manual first.

I didn't test vanilla emacs + org-roam, so I'm sure if it is caused by Spacemacs, but why not create the path according to `org-roam-directory` if the directory doesn't exist, since org-roam already sets a default value for `org-roam-directory` variable but doesn't handle the situation that the path doesn't exist.

**Comment by jethrokuan** [comment]
Like I said, `org-roam` doesn't require that the directory exists, and will not throw an error if it doesn't it just doesn't do anything. It's `imenu` that's causing your error here.

**Comment by c02y** [comment]
Thanks. It is caused by spacemacs then. I'll report this issue there.
