### ISSUE TITLE
roam v2 , org-roam-server, error "Cannot open load file: No such file or directory, org-roam-buffer"

### ISSUE THREAD

**Issue by Imymirror** [org-roam/org-roam#1649]
recently , I try to switch to roam v2. 

when I package-reinstall org-roam-server, cause an error : 
```
"Cannot open load file: No such file or directory, org-roam-buffer"
```
or this error: 
```
(error "Unknown specializer org-roam-node")
```

**Comment by nobiot** [comment]
`org-roam-server` is not compatible with Org-roam V2.
There is a reason to be excited about the upcoming update, though :)
https://github.com/org-roam/org-roam-server/issues/161

**Comment by OrionRandD** [comment]
I have the same error here after upgrading to org-roamV2.
I will comment org-roam-server lines in my config.el 
To stop org-roam-server complaining about
"Cannot open load file: No such file or directory, org-roam-buffer"
So it will be on hold...
I use doom-Emacs

Am I right doing this for now?
Since org-roam-server does not work with org-roamV2 for now?
Thx

**Comment by nobiot** [comment]
I don’t see why that could be an issue.
