### ISSUE TITLE
it should be possibile to create org-roam files in subdirectories from org-roam-node-find

### ISSUE THREAD

**Issue by molok** [org-roam/org-roam#1829]
### Brief Abstract
There are org-roam users that rely on directory structures for tagging, so it should be possible to create a org-roam file in a sub-directory of org-roam-directory

### Long Description
When using `org-roam-node-find` to create a new node (file) it would be useful to be able create a file in a `org-roam-directory` sub-directory, right now I have to create the file and then move it. IMHO typing `recipes/lasagna` should (at least optionally) create the new org-roam file under the directory `recipes`. Right now it creates a file named `${timestamp}-recipes_lasagna.org`, I'd like for it to create `recipes/${timestamp}-lasagna.org`

### Please check the following:

- [X] No similar feature requests

**Comment by molok** [comment]
something like this is possibile with capture templates, so I'm closing this

**Comment by ajz3d** [comment]
I intend to rewrite my personal `orgmode` knowledge base into `org-roam`, so I'm interested in this too. In my KB I have plenty of nested subheadings with the same name as subheadings from other places in my document. This is inevitable. So, defining an adequate directory structure for `org-roam` intuitively feels like the proper way to follow in order to avoid situations, where I am shown a couple of identical filenames, while capturing a new entry or linking to some other place in my KB. @molok mentioned that this is covered by capture templates. I browsed `org-roam` documentation:
[https://www.orgroam.com/manual.html#The-Templating-System](url):

> See the `org-roam-capture-templates` documentation for more details and customization options. 

but there's no link to documentation about `org-roam-capture-templates` in this document. So where can I find more information about it?

**Comment by molok** [comment]
@ajz3d hoping it might be useful to you, I'll share my configuration that lets me file a note in 4 different folders: a default one (root), programming/, work/ and personal/

    (setq org-roam-capture-templates
          '(
            ("d" "default" plain "%?"
             :target (file+head "%<%Y%m%d%H%M%S>-${slug}.org"
                                "#+title: ${title}\n") :unnarrowed t)
            ("p" "programming" plain "%?"
             :target (file+head "programming/%<%Y%m%d%H%M%S>-${slug}.org"
                                "#+title: ${title}\n") :unnarrowed t)
            ("w" "work" plain "%?"
             :target (file+head "work/%<%Y%m%d%H%M%S>-${slug}.org"
                                "#+title: ${title}\n") :unnarrowed t)
            ("P" "personal" plain "%?"
             :target (file+head "personal/%<%Y%m%d%H%M%S>-${slug}.org"
                                "#+title: ${title}\n") :unnarrowed t)
            )
          )

**Comment by ajz3d** [comment]
@molo, many thanks for that snippet. It was very useful indeed.
I also found plenty of information about `org-roam-capture-templates` inside `org-roam-capture.el`.
