### ISSUE TITLE
How to follow the link at point using the data from the database?

### ISSUE THREAD

**Issue by rdrg109** [org-roam/org-roam#1865]
This is a question, not a feature request nor a bug report.

### Brief Abstract

How to follow the link at point using the data from the database?

### Long Description

Before knowing of org-roam I used to follow `id:` links by using `org-open-at-point` (C-c C-o). This function indexes the location of each id in the variable `org-id-locations`.

Now that I'm using `org-roam`, I think having `org-id-locations` is redundant because the data is already indexed in the Org Roam database.

For this reason, I am wondering: Is there any function that follows the link at point by using the data in the Org Roam database?

In general terms, the question is: Given an ID as an string, is it possible to open the node whose ID is the given one?

**Comment by rdrg109** [comment]
I've created the following two functions to accomplish this

```

(defun org-roam-visit-node-with-id-at-point ()
  "Follow id link at point"
  (interactive)
  (let* ((element (org-element-context))
         (type (org-element-type element))
         link-type
         link-path
         result
         file
         pos)
    (unless (eq type 'link)
      (error "The cursor is not on a link."))
    (setq link-type (org-element-property :type element))
    (unless (equal link-type "id")
      (error "The cursor is not on a id link."))
    (setq link-path (org-element-property :path element))
    (unless link-path
      (error "The path of the link is empty."))
    (org-roam-visit-node-with-id link-path)))
```
```
(defun org-roam-visit-node-with-id (id)
  "Find node with a given ID"
  (catch 'done
    (when (eq id nil)
      (throw 'done t))
    (let ((result (org-roam-db-query [:select [file pos]
                                              :from nodes
                                              :where (= id $s1)]
                                     id)))
      (unless result
        (error "A node with the given id wasn't found."))
      (setq file (caar result))
      (setq pos (cadar result))
      (find-file file)
      (goto-char pos))))
```

**Comment by Wetlize** [comment]
> Now that I'm using org-roam, I think having org-id-locations is redundant because the data is already indexed in the Org Roam database.

It's still useful to integrate with `org-id`, unless you absolutely sure that entries from your `org-roam-directory` won't be referenced anywhere outside. Plus, it's not necessary that all entries that have ID are nodes (see `org-roam-db-node-p` function), but this is again, something optional.

> Before knowing of org-roam I used to follow id: links by using org-open-at-point (C-c C-o). This function indexes the location of each id in the variable =org-id-locations.

You don't need any extra code, Org-roam already resolves recognized links in its database, and then if it cannot find it here, it automatically fallbacks to org-id's plain text database. This is the relevant code:

https://github.com/org-roam/org-roam/blob/1795039ab93ef19611dbb3fca21c4211c4e655a9/org-roam-node.el#L608-L641

So when you use `org-open-at-point` it will automatically do the right thing.

**Comment by Konubinix** [comment]
If the topic of the issue is to make roam notes available by id links from outside the org-roam directory, this answer is incomplete.

The magic is indeed that `org-roam-open-id-at-point` is added to the `org-open-at-point-functions` hook. That way, following an id link will find the roam note. But if you look closer, you will find out that this hook is added only locally to roam notes.

This means you can only follow id links from roam notes to roam notes.

If you want to follow id links from outside roam notes, add this to your .emacs `(add-hook 'org-open-at-point-functions #'org-roam-open-id-at-point))` to enable this behavior from everywhere.

If, like me, you want a more deep integration, you can use a code that makes `org-id-find` find roam notes as well as stuff in `org-id-locations`. This is how I did it https://github.com/Konubinix/Devel/blob/master/elfiles/config/after-loads/KONIX_AL-org-roam.el#L197

That way, not only `org-open-at-point` will find the roam note, but also code using `(org-id-find someid)` will find roam notes in addition to traditionnal org headings. Hope that helps.

**Comment by jethrokuan** [comment]
To summarize this discussion:

1. `org-roam-open-id-at-point` is the function used to follow the link at point from the database.
2. This is called via `org-open-at-point-functions`: meaning if Org-roam is able to find the ID at point in the database it is able to use it to navigate to the point.
3. This function is currently only added buffer-locally within roam notes: you can add it globally via:

```emacs-lisp
(add-hook 'org-open-at-point-functions #'org-roam-open-id-at-point)
```
