### ISSUE TITLE
Use slug as custom org ID

### ISSUE THREAD

**Issue by xeruf** [org-roam/org-roam#1935]
### Brief Abstract

I would like the id to set to the slug on capture, making adjustments easier.
I dislike having full UUIDs as ids.

### Proposed Implementation (if any)

A customization variable to change how the ID is generated.

### Please check the following:

- [x] No similar feature requests

**Comment by nobiot** [comment]
You can already do what you ask for.

Add properties directly in your `org-roamm-capture-templates` with `id` and its value `${slug}` like this example below.

```
          ("t" "test Org" plain "%?" :if-new
           (file+head "personal/${title}.org"
                      ":properties:\n:id: ${slug}\n:modified: <>\n:end:\n#+title: ${title}\n")
           :unnarrowed t)
```

You get something like this. The slug ID is recognised by Org-roam as you can see from the minibuffer showing the result of `org-roam-node-find`.

![image](https://user-images.githubusercontent.com/12507865/140603781-5bcc12aa-553e-49a4-aad3-4f8a02fbf2e1.png)

Backlink works, too.
![image](https://user-images.githubusercontent.com/12507865/140603905-bd897dc6-f733-4a39-a1bd-68da451d2144.png)

**Comment by nobiot** [comment]
@xeruf I think you might like to note is that this "custom ID" is only recognised within Org-roam.
The built-in Org-ID does not recognise custom IDs. This means Org files outside `org-roam-directory` won't be able to find the custom IDs. One way to solve this is to run the `org-roam-update-org-id-locations` command manually.

For your preference of not using UUID (I guess because of its visual clutter), you might find [this recent thread](https://org-roam.discourse.group/t/turn-off-the-bright-meta/2174/9) in the Discourse forum interesting

**Comment by jethrokuan** [comment]
If you don't want full uuids, customize `org-id-method`, as per the Org manual.

**Comment by xeruf** [comment]
> @xeruf I think you might like to note is that this "custom ID" is only recognised within Org-roam. The built-in Org-ID does not recognise custom IDs. This means Org files outside `org-roam-directory` won't be able to find the custom IDs. One way to solve this is to run the `org-roam-update-org-id-locations` command manually.

This does not make sense to me - I thought the properties drawer is meant to be org-native? Why does it care about the format of the id?

> For your preference of not using UUID (I guess because of its visual clutter), you might find [this recent thread](https://org-roam.discourse.group/t/turn-off-the-bright-meta/2174/9) in the Discourse forum interesting

Indeed. My concern is being able to link pages quickly by hand through memorable ids as well as the attachment file structure making sense now that I use org-attach.
Due to my use of custom IDs I would actually appreciate org-roam-find-file to also find files through matching to the ID, would this be possible to configure?

**Comment by nobiot** [comment]
Yes it will work. Try it yourself; you don’t have to believe me. Jethro’s suggestion is also helpful. 

It’s not the format that matters; it’s the function you use. If you don’t use a built-in function, you may be missing some elements of outcome you expect from it.

**Comment by memeplex** [comment]
> If you don't want full uuids, customize org-id-method, as per the Org manual.

The method can only take a handful of predefined values (org, uuid and ts) so it won't do it for slugs. That said, it's very easy to redefine `org-id-new` although perhaps the OP doesn't want to alter it globally. @nobiot suggestion to include properties in the capture template is an excellent solution and note that you can even call your own functions in the template, for example:
```
":properties:\n:id: ${my-whimsical-slug}\n:modified: <>\n:end:\n#+title: ${title}\n"
```
I believe org-roam already provides what is requested here and there is not much room for improvement.

>> I think you might like to note is that this "custom ID" is only recognised within Org-roam.
The built-in Org-ID does not recognise custom IDs.

> This does not make sense to me - I thought the properties drawer is meant to be native to org? Why does the format of the id make a difference?

Don't worry about this, org doesn't care about the format of IDs (except, of course, when creating them). You will have to ensure unicity though.

**Comment by nobiot** [comment]
@memeplex Thanks for the additional comments.

For both... Let me add to what I said earlier:

>  It’s not the format that matters; it’s the function you use. If you don’t use a built-in function, you may be missing some elements of outcome you expect from it.

Have a look at the two screen images below.

![Screenshot from 2021-11-08 18-52-13](https://user-images.githubusercontent.com/12507865/140793481-fdd6f31f-09ac-4788-9593-6de0568d1a7c.png)

![Screenshot from 2021-11-08 18-53-47](https://user-images.githubusercontent.com/12507865/140793564-503a32f5-cfaa-4313-bda0-4fc8c0fb549e.png)

As you can see in the notes in the screens, you can add an ID manually to an Org file. Within Org-roam, it gets put into the cache and thus other notes within `org-roam-directory` recognise it with no issues.

The Org files outside Org-roam won't recognise such IDs by default. This is because Org-id uses a hash table and a file `org-id-locations-file` to keep track of IDs and their associated filenames. By manually assigning an ID to an Org file (outside Org-roam), you are bypassing this mechanism. 

In order to get your manual IDs into the hash table and the Org-ID file, you need to use some functions. Built-in Org-id functions such as `org-id-get-create` takes care of this. This is what I meant by "built-in functions do more than looking at the format and properties" above.

You can use these commands/function to update the hash and the location file.

- `org-roam-update-org-id-locations`
- `org-id-update-id-locations`
- `org-id-add-location`

@xeruf

**Comment by memeplex** [comment]
> For both... Let me add to what I said earlier:

>> It’s not the format that matters; it’s the function you use. If you don’t use a built-in function, you may be missing some elements of outcome you expect from it.

Oh, yes, I was just trying to stress this. When you use the verb "recognize" as in "org won't recognize such ids" it may seem, especially in the context of the OP's requirement, that it's the format that's not recognized. Let's say that "org won't find such ids". I would also add that this is not only unrelated to the format but also unrelated to any additional constraint org-roam may be imposing: the same would happen if you manually set ids without org-roam existing at all. It's because of the way org-id works, not org-roam.

**Comment by xeruf** [comment]
> It’s not the format that matters; it’s the function you use. If you don’t use a built-in function, you may be missing some elements of outcome you expect from it.
>
> In other words, built-in functions do more than looking at the format and properties… You will see this by inspecting org-id functions.

I do not see `org-id-new` doing any magic, only `org-id-get` putting it in the id database.
So I guess I could add a hook to update the db after capturing a roam file.

Anyways, the templates are an excellent idea. Actually, I want to create multiple templates and do some deduplication via variables, but this does not work as the variable names are taken literally. How can I prevent this?
```elisp
(setq my/org-roam-capture-props ":properties:\n:id: ${slug}\n:created: %<%Y-%m-%dT%H%M%S>\n:modified: <>\n:end:\n")
(setq my/org-roam-capture-title "#+title: ${title}\n")
(setq my/org-roam-capture-template (concat my/org-roam-capture-props my/org-roam-capture-title))
(setq org-roam-capture-templates
      '(("d" "default" plain "%?" :target
         (file+head "%<%Y%m%d>-${slug}.org" 'my/org-roam-capture-template)
        :unnarrowed t))
     )
```

**Comment by xeruf** [comment]
Btw how does this modified property work?

**Comment by jethrokuan** [comment]
> How can I prevent this?

By evaluating them:

**Comment by xeruf** [comment]
Ah, I had the comma but was missing the backtick, thank you very much!

**Comment by xeruf** [comment]
@nobiot by the by, how does this `modified` property work? It does not seem like you have dotfiles publicly available, otherwise I would have looked myself ;)

**Comment by nobiot** [comment]
It’s this https://github.com/org-roam/org-roam/wiki/User-contributed-Tricks#timestamp-on-save-alanz

My way is slightly different but using the same method:
https://git.sr.ht/~nobiot/stow/tree/main/item/emacs/.config/emacs/lisp/init-editor.el#L9

**Comment by xeruf** [comment]
I like it a lot, thank you all :)
