### ISSUE TITLE
Error linking node when there are 2+ nodes with same title or alias. Implement a way to select nodes that have same title.

### ISSUE THREAD

**Issue by yuuyins** [org-roam/org-roam#2043]
### Brief Abstract
Error linking node when there are 2+ nodes with same title or alias. Implement a way to select nodes that have same title.

### Long Description
Org-roam allows creating nodes with same title/alias, but doesn't handle their liking and throws an error instead "Multiple nodes exist with title or alias". https://github.com/org-roam/org-roam/blob/001de3a874cc7d8c2b94eea49abdb71c398ade64/org-roam-node.el#L265
This is mostly an issue because with the node logic in v2, the user can have a file with title or alias TITLE, and a file with heading/subheading TITLE that is a node. A familiar solution would be that displayed in org-roam-node-find which displays the structure for nodes that are headings/subheading like "A > B > C". I have no idea though about a solution for files with same title.

### Please check the following:

- [X] No similar feature requests

**Comment by jethrokuan** [comment]
I'm inclined to say that if you're seeing multiple nodes with the same title or alias, then you're not using Org-roam the way it is designed to be used.

As you can imagine handling name clashes requires special care, and the hole runs deep. There are many things to consider and it results in convoluted and branched code that needs maintaining. My personal take is that it's not worth it. Your nodes should really be [atomic and specific](https://notes.andymatuschak.org/z4Rrmh17vMBbauEGnFPTZSK3UmdsGExLRfZz1?stackedNotes=z3XP5GRmd9z1D2qCE7pxUvbeSVeQuMiqz9x1C).

That said, I'm open to any PRs that can present a clean solution.

**Comment by yuuyins** [comment]
@jethrokuan it is not that I'm creating nodes with same title for the same purpose. For example, I created an org file with title finance for describing finance in itself. In another org file, I created a heading finance that is related to my personal financial transactions related to the subject of that file and made it a node so that I can easily find it with org-roam-node-find on Doom Emacs.

**Comment by jethrokuan** [comment]
@yuuyins I understand, but that's the sort of structure I'm discouraging. Anyway, this limitation currently only applies to `roam:` style links. You can use hierarchy if you want via the regular interactive commands, as [the wiki](https://github.com/org-roam/org-roam/wiki/User-contributed-Tricks#showing-node-hierarchy) illustrates.

**Comment by xbc5** [comment]
If I create two nodes `baz` and `foo > baz > baz`, both of those are `[[roam:baz]]` when using auto-complete, and will collide. When saving the file, org-roam complains -- that's the issue. I have to manually delete the link, type out the word, highlight it, then manually fix each link. Using auto-complete is important when typing notes so that I stay in flow, and `foo > bar > baz` doesn't apply here.

SOLUTION: I'd like a fuzzy buffer to open on save, that goes through each collision one-by-one, clearly highlighting the word, and allow me to select based on tags and title. Doing that "on save" is important because I don't want to break my flow when typing.

If my elisp were up to scratch I'd contribute. I take a shot if this issue is still open in a few weeks. :) 

Just to add some context: nodes are a **global namespace**, and there will always be collisions. The only two ways to avoid this are to 1) use an ever increasing node name size; 2) provide a means to resolve issues. Also, verbose titles are fine, that's what aliases are for (they're good for auto-complete), but selecting a verbose title in auto-complete leads to ugly notes.
