### ISSUE TITLE
Saving a narrowed buffer fails

### ISSUE THREAD

**Issue by simendsjo** [org-roam/org-roam#2139]
### Description

Looks like narrowing breaks saving files. I get the following when I save a narrowed file

```
condition-case: Error in a Doom startup hook: after-save-hook, org-roam-db-autosync--try-update-on-save-h, (emacsql-constraint "FOREIGN KEY constraint failed")
```

Adding `(widen)` to `org-roam-db-update-file` fixes the issue (but doesn't renarrow after `save-excursion` ends)

### Environment

```
Copy info below this line into issue:
- Emacs: GNU Emacs 28.0.92 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0)
 of 2022-03-25
- Framework: Doom
- Org: Org mode version 9.6 (9.6-??-e7ea951 @ /home/simendsjo/.emacs.d/.local/straight/build-28.0.92/org/)
- Org-roam: v2.2.0-16-geed1df9
```

**Comment by ComedyTomedy** [comment]
I think I've got the same error on vanilla emacs. It seems to be when the buffer is narrowed enough to exclude a header with an :ID:. Saving and `org-roam-db-sync` both throw an error.

`save-excursion` doesn't deal with narrowing, there's `save-restriction` for that, so if we throw that in, you might have the solution :) Note that they need to be embedded in that particular order `(save-excursion (save-restriction ...))`, & not the other way around.

(I don't really know the reason for this, but I think it's something like - due to the way that `save-excursion` occasionally monkeys with buffer identities, save-restriction would sometimes find itself trying to restore something that no longer exists)
