### ISSUE TITLE
Uses builtin support for SQLite

### ISSUE THREAD

**Issue by Eason0210** [org-roam/org-roam#2146]
`emacsql-libsqlite3` have been renamed to  `emacsql-sqlite-builtin` to uses builtin support for SQLite, which was added in Emacs 29.

https://github.com/emacscollective/emacsql-sqlite-builtin
https://melpa.org/#/emacsql-sqlite-builtin

And we can not customize `org-roam-database-connector` to use `emacsql-libsqlite3`
Please update Org-roam to adapt it.

https://github.com/org-roam/org-roam/blob/36152590ad1e8ffea86cb909e5ef818cbdb2a22d/org-roam-db.el#L37-L55

**Comment by tarsius** [comment]
Came here to mention that. :grinning: 

You should support both `emacsql-sqlite-module` (which is just `emacsql-libsqlite3` renamed for consistency) and `emacsql-sqlite-builtin`.

See the code in `epkg` and `forge` that does the same (and which the current implementation in `org-roam` is based on).

Note in particular that I dropped the `(symbol :tag "other")` from my packages. Your usage is a bit simpler so you could support arbitrary other backends but the value would probably have to have the form `(FEATURE . FUNCTION)`, not just `FUNCTION` and you would also have to add support in `org-roam-db--conn-fn`. Probably not worth it.

**Comment by Eason0210** [comment]
@jethrokuan 

I tested latest commit with `emacsql-sqlite-builtin` by setting
```emacs-lisp
  (setq-default org-roam-database-connector 'sqlite-builtin)
```
but I always got this error:
``` 
Error (use-package): org-roam/:config: Cannot open load file: No such file or directory, emacs-sqlite-builtin
```
I think this should be a typo in [org-roam-db.el ]( https://github.com/org-roam/org-roam/blob/master/org-roam-db.el#L166-L171)

`(require 'emacs-sqlite-builtin)` should be  `(require 'emacsql-sqlite-builtin)`
`(require 'emacs-sqlite-module)`  should be `(require 'emacsql-sqlite-module)`

But when I fixed it locally, I will got this error when execute `org-roam-node-find`:

```
Error (use-package): org-roam/:config: Wrong type argument: processp, #<sqlite db=0x7feb6fa25b50 name=/Users/eason/.org/org-roam.db>
```

my org-roam config:
```emacs-lisp
(use-package org-roam
  :diminish
  :bind (("C-c n a" . org-id-get-create)
         ("C-c n l" . org-roam-buffer-toggle)
         ("C-c n f" . org-roam-node-find)
         ("C-c n g" . org-roam-graph)
         ("C-c n i" . org-roam-node-insert)
         ("C-c n c" . org-roam-capture)
         ("C-c n j" . org-roam-dailies-capture-today)
         ("C-c n r" . org-roam-ref-find)
         ("C-c n R" . org-roam-ref-add)
         ("C-c n s" . org-roam-db-sync))
  :init
  (setq-default org-roam-database-connector 'sqlite-builtin)
  (setq org-roam-directory (file-truename "~/.org/org-roam")
        org-roam-db-location "~/.org/org-roam.db"
        org-roam-db-gc-threshold most-positive-fixnum
        org-roam-v2-ack t)
  (unless (file-exists-p org-roam-directory)
    (make-directory org-roam-directory t))
  :config
  (org-roam-db-autosync-enable)
  (add-to-list 'display-buffer-alist
               '("\\*org-roam\\*"
                 (display-buffer-in-direction)
                 (direction . right)
                 (window-width . 0.33)
                 (window-height . fit-window-to-buffer))))
```

Tested on Emacs 29.0.50  @ macOS 12.3.1

**Comment by Eason0210** [comment]
👍  Great ! Now it works well！

**Comment by mtekman** [comment]
Apologies for bumping but I'm getting this exact same error message:

`Error (use-package): org-roam/:config: Cannot open load file: No such file or directory, emacs-sqlite-builtin`

My config is exactly the same as @Eason0210 's above, with `(use-package emacsql-sqlite-builtin)` defined underneath.

The reason I'm bumping instead of opening a new issue is that I think it might be an issue with `straight.el` (which I use to clone and build packages) instead of an issue with org-roam.

If anyone is using `straight.el` on Emacs 29.0.60, you may be getting the same error.

# Solution

When installing `emacsql-sqlite-builtin`, note that  straight.el:
* Clones the repo to `~/.emacs.d/straight/repos/emacsql`
* Builds the package at:  `~/.emacs.d/straight/build/emacsql-sqlite-builtin`

In the build directory, it symlinks only to:
* emacsql-sqlite-builtin.el ⇒ ~/.emacs.d/straight/repos/emacsql/emacsql-sqlite-builtin.el

To fix the error, you need to manually add two more symlinks that straight.el seems to miss:

* emacsql-sqlite-common.el ⇒ ~/.emacs.d/straight/repos/emacsql/emacsql-sqlite-common.el
* emacsql-sqlite.el ⇒ ~/.emacs.d/straight/repos/emacsql/emacsql-sqlite.el

After this, it should not longer give the errors.

**Comment by IvanMalison** [comment]
@mtekman the common file and emacssql-sqlite should be part of the emacs-sqlite pacakge, which is a dependency of the built in package.
