### ISSUE TITLE
Data saved in the database has spurious " around

### ISSUE THREAD

**Issue by dmgerman** [org-roam/org-roam#2237]
### Description

Several fields in the sqlite database are wrapped by quotes ("")

#### Steps to Reproduce

run sqlite on the roam database:

```
sqlite> select file, hash from  files limit 3;
file                                                              hash                                      
----------------------------------------------------------------  ------------------------------------------
"/home/dmg/tmDropbox/org/roam/20210731143057-learning_emacs.org"  "5fb5bf81a695d006c8f446366ad56d2b47298048"
"/home/dmg/tmDropbox/org/roam/20211206111910-git.org"             "d0908eb5d1184b4d981628169c78025ae150257a"
"/home/dmg/tmDropbox/org/roam/20210724224516-karube.org"          "62db38d7f4f27a490ad867fd858b5eac075ec48b"
sqlite> select tag from tags;
tag       
----------
"todo"    
sqlite> select tag from tags where tag = '"todo"';
tag       
----------
"todo"    

```

#### Expected Results

It makes queries on the database more complex than necessary.

#### Actual Results

- Emacs: GNU Emacs 28.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0)
 of 2022-05-30
- Framework: I don't know
- Org: Org mode version 9.5.2 (release_9.5.2 @ /home/dmg/.emacs.d/org-mode/lisp/)
- Org-roam: 2.0.0

**Comment by Delapouite** [comment]
Hello

My understanding of the way org-roam data is saved in the db, is that it favors raw elisp atoms. It makes it quite transparent for the underlying library (https://github.com/skeeto/emacsql) to read and write stuffs directly from emacs code.

On the other hand, as you mentioned, it is less convenient for third party tools / languages that want to perform analysis on this same data.

In my opinion, having these extra quotes is okayish. What's more cumbersome is the way dates are stored, for instance the files `atime` and `mtime` look something like this `(24987 64489 97759 713000)` instead of Unix epoch timestamps.

Also the `properties` column of the nodes table is an elisp `alist`, where a JSON object would have opened more perspective for querying thanks to the recent additions in SQLite capabilities.

**Comment by jethrokuan** [comment]
This is just an artifact of how emacsql uses sqlite: it reads and writes emacs objects by serializing and deserializing them when writing and reading from the database. Maybe as Emacs gains better native sqlite support, this may change.
