### ISSUE TITLE
Has org-roam-node-list been removed

### ISSUE THREAD

**Issue by frumigoul** [org-roam/org-roam#2357]
### Description
I am trying to improve the configuration of my org-roam config, according to the example of [David Wilson](https://systemcrafters.net/build-a-second-brain-in-emacs/5-org-roam-hacks/), but I get an error message regarding the missing function `org-roam-node-list`

#### Steps to Reproduce

Example:

1. Install Emacs 28 / org-roam 2.2.2.42
2. integrate the config of David Wilson's post (link above)
3. Start emacs and load the config
...

#### Backtrace
   Debugger entered--Lisp error: (void-function org-roam-node-list)
  (org-roam-node-list)
  (seq-filter (my/org-roam-filter-by-tag tag-name) (org-roam-node-list))
  (mapcar #'org-roam-node-file (seq-filter (my/org-roam-filter-by-tag tag-name) (org-roam-node-list)))
  my/org-roam-list-notes-by-tag("Project")
  (setq org-agenda-files (my/org-roam-list-notes-by-tag "Project"))
  my/org-roam-refresh-agenda-list()
  eval-buffer(#<buffer  *load*> nil "/home/fred/.emacs.d/init.el" nil t)  ; Reading at buffer position 93895
  load-with-code-conversion("/home/fred/.emacs.d/init.el" "/home/fred/.emacs.d/init.el" t t)
  load("/home/fred/.emacs.d/init" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode 0x1ac43e1fc1142638>) #f(compiled-function () #<bytecode -0x1f3c61addc0b8a75>) t)
  command-line()
  normal-top-level()

#### Expected Results
no error messagem the whole config is loaded successfully

#### Actual Results

Error message shown: "Debugger entered--Lisp error: (void-function org-roam-node-list)" 
### Environment

version 2.2.2.42

**Comment by progfolio** [comment]
The code at https://systemcrafters.net/build-a-second-brain-in-emacs/5-org-roam-hacks/ incorrectly assumes org-roam-node is loaded. Adding a `(require 'org-roam-node)` in the body of the functions which rely on org-roam-node.el's functions should prevent the error.

**Comment by pauljamesharper** [comment]
Thanks to progfolio I got it working with this config:

`* Org-Roam
#+begin_src emacs-lisp
(use-package org-roam
  :ensure t
  :demand t  ;; Ensure org-roam is loaded by default
  :init
  (setq org-roam-v2-ack t)
  :custom
  (org-roam-directory "~/Dropbox/org/org-roam")
  (org-roam-completion-everywhere t)
  :bind (("C-c n l" . org-roam-buffer-toggle)
         ("C-c n f" . org-roam-node-find)
         ("C-c n i" . org-roam-node-insert)
         ("C-c n I" . org-roam-node-insert-immediate)
         ("C-c n p" . my/org-roam-find-project)
         ("C-c n t" . my/org-roam-capture-task)
         ("C-c n b" . my/org-roam-capture-inbox)
         :map org-mode-map
         ("C-M-i" . completion-at-point)
         :map org-roam-dailies-map
         ("Y" . org-roam-dailies-capture-yesterday)
         ("T" . org-roam-dailies-capture-tomorrow))
  :bind-keymap
  ("C-c n d" . org-roam-dailies-map)
  :config
  (require 'org-roam-dailies) ;; Ensure the keymap is available
  (org-roam-db-autosync-mode))

(defun org-roam-node-insert-immediate (arg &rest args)
  (interactive "P")
  (let ((args (push arg args))
        (org-roam-capture-templates (list (append (car org-roam-capture-templates)
                                                  '(:immediate-finish t)))))
    (apply #'org-roam-node-insert args)))

(defun my/org-roam-filter-by-tag (tag-name)
  (lambda (node)
    (member tag-name (org-roam-node-tags node))))

(defun my/org-roam-list-notes-by-tag (tag-name)
  (require 'org-roam-node)
  (mapcar #'org-roam-node-file
          (seq-filter
           (my/org-roam-filter-by-tag tag-name)
           (org-roam-node-list))))


(defun my/org-roam-refresh-agenda-list ()
  (interactive)
  (require 'org-roam-node)
  (setq org-agenda-files (my/org-roam-list-notes-by-tag "Project")))


(defun my/org-roam-project-finalize-hook ()
  "Adds the captured project file to `org-agenda-files' if the
capture was not aborted."
  ;; Remove the hook since it was added temporarily
  (remove-hook 'org-capture-after-finalize-hook #'my/org-roam-project-finalize-hook)

  ;; Add project file to the agenda list if the capture was confirmed
  (unless org-note-abort
    (with-current-buffer (org-capture-get :buffer)
      (add-to-list 'org-agenda-files (buffer-file-name)))))

(defun my/org-roam-find-project ()
  (interactive)
  ;; Add the project file to the agenda after capture is finished
  (add-hook 'org-capture-after-finalize-hook #'my/org-roam-project-finalize-hook)

  ;; Select a project file to open, creating it if necessary
  (org-roam-node-find
   nil
   nil
   (my/org-roam-filter-by-tag "Project")
   :templates
   '(("p" "project" plain "* Goals\n\n%?\n\n* Tasks\n\n** TODO Add initial tasks\n\n* Dates\n\n"
      :if-new (file+head "%<%Y%m%d%H%M%S>-${slug}.org" "#+title: ${title}\n#+category: ${title}\n#+filetags: Project")
      :unnarrowed t))))

(defun my/org-roam-capture-inbox ()
  (interactive)
  (org-roam-capture- :node (org-roam-node-create)
                     :templates '(("i" "inbox" plain "* %?"
                                  :if-new (file+head "Inbox.org" "#+title: Inbox\n")))))

(defun my/org-roam-capture-task ()
  (interactive)
  ;; Add the project file to the agenda after capture is finished
  (add-hook 'org-capture-after-finalize-hook #'my/org-roam-project-finalize-hook)

  ;; Capture the new task, creating the project file if necessary
  (org-roam-capture- :node (org-roam-node-read
                            nil
                            (my/org-roam-filter-by-tag "Project"))
                     :templates '(("p" "project" plain "** TODO %?"
                                   :if-new (file+head+olp "%<%Y%m%d%H%M%S>-${slug}.org"
                                                          "#+title: ${title}\n#+category: ${title}\n#+filetags: Project"
                                                          ("Tasks"))))))

(defun my/org-roam-copy-todo-to-today ()
  (interactive)
  (let ((org-refile-keep t) ;; Set this to nil to delete the original!
        (org-roam-dailies-capture-templates
          '(("t" "tasks" entry "%?"
             :if-new (file+head+olp "%<%Y-%m-%d>.org" "#+title: %<%Y-%m-%d>\n" ("Tasks")))))
        (org-after-refile-insert-hook #'save-buffer)
        today-file
        pos)
    (save-window-excursion
      (org-roam-dailies--capture (current-time) t)
      (setq today-file (buffer-file-name))
      (setq pos (point)))

    ;; Only refile if the target file is different than the current file
    (unless (equal (file-truename today-file)
                   (file-truename (buffer-file-name)))
      (org-refile nil nil (list "Tasks" today-file nil pos)))))

(add-to-list 'org-after-todo-state-change-hook
             (lambda ()
               (when (equal org-state "DONE")
                 (my/org-roam-copy-todo-to-today))))
#+end_src
`

**Comment by frumigoul** [comment]
It does, thanks for the hint.
The ticket can be closed.

----------------------------------------

29 juin 2023 17:54:36 Nicholas Vollmer ***@***.***>:
