### ISSUE TITLE
support relative file path

### ISSUE THREAD

**Issue by zbelial** [org-roam/org-roam#495]
### Brief Abstract
I want to use github to store my notes and edit them on two computers with different file system layout. Now the only way to support my use case is not to share org-roam.db and to build separately the cache on each computer, which is not convenient. 

### Proposed Implementation (if any)
If supporting relative file path is not conflict with this package's design, I can make a PR for review.

### Please check the following:
- [x ] No similar feature requests

**Comment by mathiasp** [comment]
I would also love to see this feature.

One question for me is if this should be configurable. Jethro, what is you opinion on this?

I think  the concept behind roam / smart notes as a life long repository supports abbreviated file names, since i do not expect the absolute paths will stay the same for the lifetime of my roam files.

I have startet to patch my local copy of roam to support this, using abbreviate-file-name, 

I'm just thinking if it's a good idea to hide this behind something like org-roam--canonical-file-name to make it switchable, but are now unsure if this is a good way to go.

My test setup will be emacs FreeBSD and android && termux, but I'm not yet ready.

**Comment by zbelial** [comment]
Hi @mathiasp 
I've implemented it in the following way:  
1. Add a custom variable, which is a LABEL attached to `org-roam-directory`
2. When saving filenames to db, replace `org-roam-directory` part ot the file name with the LABEL
3. After reading filenames back from db, replace LABEL with `org-roam-directory`

In this way, you can use whatever path as `org-roam-directory` and share org-roam data between computers. 
You can find the changes in my fork's `relative` branch. 
Any sugguestion?

**Comment by zaeph** [comment]
I believe we store absolute paths to the files in the database for rigidity, but we might be able to make it relative to `org-roam-directory`.  Then, all you'd need to do is to define system-specific variable assignments to ensure that `org-roam-directory` points to the right place.

For `org-roam--extract-links`, here's where we're using absolute paths:
https://github.com/jethrokuan/org-roam/blob/fbdda33c6a9bcc01f1bf5550f0bf7d3ea817670e/org-roam.el#L239-L240

We'd need to modify a few of the retrieving functions to ensure that the relative-paths are converted to absolute, but I think this would be doable.

@jethrokuan: Is there something that I'm missing?

**Comment by jackbaty** [comment]
I just ran into this myself after trying to use org-roam on Linux after using it and building the database on my Mac (all paths are stored as "/Users/jbaty...."), so this issue is pertinent to me also. I could configure the db to live somewhere not shared, as the OP mentioned, but ideally I wouldn't have to. Thanks.

**Comment by jethrokuan** [comment]
The DB has now defaulted to a location that shouldn't be synced across multiple machines.

In v2, Org-roam uses ID links, which is also more resilient to change.
