### ISSUE TITLE
Autocomplete and create new pages

### ISSUE THREAD

**Issue by mimischi** [org-roam/org-roam#510]
### Brief Abstract

I would like to be able to type `[[`, have it autocomplete to `[[_]]` (`_` is the cursor) and type any page name. If it does not exist, it should be created. Similar to how RoamResearch does it.

### Long Description

RoamResearchs allows to type `[[` and autocompletes it to `[[_]]` (with `_` being your cursor). It then autocompletes a) existing page names and b) allows to create a new page.

(a) Existing pages can already be referenced using [`company-org-roam`](https://github.com/jethrokuan/company-org-roam) just by typing any name. This was addressed in #421. Although this currently does _not_ work by typing `[[`.

(b) If a page does not exist, I have to trigger `org-roam-insert` first. If I am in the `insert` mode of `evil`, I first have to exit to `normal` mode and then type `SPC n i` (with `doom-emacs`) to insert a new link (even to non-existent files). This slows down my typing and I would love to be able to insert pages just as fluently as with RoamResearch.

### Proposed Implementation

As @zaeph has mentioned in the [Slack thread](https://orgroam.slack.com/archives/CV20S23C0/p1587539981023500), one needs to keep track of files that have a) no content and b) are not referenced any longer. Creating a link by typing `[[ foo` (autocompleting to `[[foo]]`) should first create a `foo.org` file. If we then change the link to `[[bar]]`, it should delete `foo.org` (if it has no content) and create `bar.org`. As far as I am aware, this would replicate the behaviour of RoamResearch.

### Please check the following:
- [x] No similar feature requests

**Comment by zaeph** [comment]
> As @zaeph has mentioned in the [Slack thread](https://orgroam.slack.com/archives/CV20S23C0/p1587539981023500), one needs to keep track of files that have a) **no content** and b) are not referenced any longer. [emphasis added]

Just to be clear, I'm not suggesting that we remove files without any content.  We'd have to create a file-metadata tag like `#+ROAM_AUTOCREATED: t` which would allow us to tag those entries, and remove them if they're not referenced anywhere else.

A few points on implementations:
1. Right now, it's possible to have an `org-capture` return immediately with `:immediate-finish t` when using `org-roam-insert`.  This prevents the `org-capture` window from spawning, and reduces the bump in the workflow.
2. We could have a custom link-handler which would create the file upon formatting.  Then, we'd clean up the orphans in `before-file-save`.
3. If we do it like this, I foresee a lag happening upon link creation, which wouldn't be too good.
4. We could handle the creation of those autocreated-notes at `before-file-save`.  Since those links would have the format `[[foo]]`, we could be able to differentiate them from complete-links, since those would have a `[[foo.org][foo]]` format.

**Comment by alan-carroll** [comment]
Recreating Roam's exact link style and function as an org-roam default seems like it might be a significant burden, not least because there is potential interference with org itself. I think a compromise may work out well instead. For clearer reference, the requested functionality is:

1. Add org-roam file-link by pressing `[[`. 
2. `[[` should call company-org-roam to autocomplete for existing org-roam files
3. If an org-roam file does not yet exist for `[[foo]]`, org-roam should create one.
a. File creation should happen without interrupting workflow
b. Changing `[[foo]]` to `[[bar]]` should delete foo.org and create bar.org, so long as foo doesn't have content.

My elisp and org knowledge are not very detailed, but `[[_]]` is already treated as a link by org -- is this something that would need a specific work around in the OR code? Or in an OR file, could this just be auto-corrected to a proper OR link? Problem is, once a proper OR link is inserted you cannot easily go back and change it just by changing `[[foo]]` to `[[bar]]` like you would in Roam -- the most efficient way to change it would be to delete the link entirely and reinsert with `[[`. 

So essentially 1. and 2. would just be a convenient and Roam-esque way to call upon existing functionality. Rather than adding these as a default, I think it makes more sense to simply add a page of documentation showing how someone can set up this shortcut themselves, noting any potential interference with org.

3 is more complex. If I understand correctly, @zaeph is suggesting that upon saving the current org file a before-file-save hook would detect links of the form `[[foo]]`, create their OR files automatically and replace `[[foo]]` with `[[file:foo.org][foo]]`. The auto-created files would have `#+ROAM_AUTOCREATED: t` added to them.

I foresee two problems with this:
1. As I already mentioned, org treats `[[foo]]` as a link and hides the details upon completion, showing just `foo`. I now cannot tell whether `foo` is a true OR link or an empty link awaiting file creation. Of course I'll remember most of the time, but this doesn't seem like a desired behavior.
2. Does a before-file-save hook run with autosaves? This would defeat the purpose of having easily editable empty links, as file creation and link changes would occur pretty frequently (at least for me). Now even if I remember all of the empty links, they may or may not be complete OR links and files.

I don't find the lag of immediate file creation with `immediate-finish: t` that troublesome. It's not as ideal as simply typing `[[` and continuing on, but everything would be a proper OR link at all times. If I want to change `foo` to `bar` I just delete the link and insert a new one. This wouldn't require any changes to org-roam; just some customization of keys and a template

If the lag is really undesirable, a regex solution might be to do like org-ref `cite:` and then supply an org-roam function to create new files and replace results with proper OR links. Something like `roam:foo subject:roam` (to allow for spaces in note titles). Now there is no lag, a custom face can be applied to instances to make them stand out, they are easily edited until creation, and the file I'm working on can be saved willy nilly and only have OR create new auto-files when you want it to by invoking `M-x org-roam-create-from-regex` or something. It would also be possible to have this be a shortcut that either inserts an OR link if a file exists or returns the regex pattern if it doesn't

In both of these solutions it will be possible to create many 'empty' OR files with just the single backlink to the org file I'm writing. If upon reflection I find I didn't really want `foo` I wanted `bar`, I now have an orphan `foo` file with no backlinks. However it's also possible that I may end up creating orphan files like these manually during normal OR usage anyway (calling `org-roam-insert` with a different template, then changing my mind later). I don't think it is really a question of whether they were automatically created (and tagged with `#+ROAM_AUTOCREATED: t`, unless someone really wants that tag). I just want to know if a file has content and/or links. These empty files, regardless of method of creation, can be found and deleted with the addition of another org-roam function or two, which can be manually invoked.

So I propose instead doing either 1 or 2 (or both) below:
1. Add documentation for personally creating a shortcut (Roam `[[` or some other personal choice) to invoke either company-org-roam or a custom org-roam-insert template with `immediate-finish: t`. This wouldn't require any changes to OR's code.
2. Add a regex and custom face for `roam:possible new note:roam`, or something similar. This can also easily be a shortcut someone can implement to save themselves 5 s. Add a function to search an org file and replace these instances with auto-created OR files and links

In both cases above, I think it is sensible to also add manual org-roam functions to remove files that a) Have no content OR links, and one for b) Have no links (or at least a list for user review, in cases where the content may be minimal or only some template defaults), regardless of whether they were auto-created or not.

Potential con to my proposal 2: Duplication of files. If a topic is referenced multiple times, OR will need to correctly create one file (or no files, if the topic actually exists already) and replace all instances with the correct link. I also suspect everyone would like auto-completion for existing regex instances to avoid misspellings (and possibly a similarity check to see if a user wants to merge very similarly named instances).

**Comment by zaeph** [comment]
> 1. As I already mentioned, org treats `[[foo]]` as a link and hides the details upon completion, showing just `foo`. I now cannot tell whether `foo` is a true OR link or an empty link awaiting file creation. Of course I'll remember most of the time, but this doesn't seem like a desired behavior.

Opening a `[[foo]]` link before it has been created would run the same functions which would be run on it with `before-save-hook`.

> 2. Does a before-file-save hook run with autosaves? This would defeat the purpose of having easily editable empty links, as file creation and link changes would occur pretty frequently (at least for me). Now even if I remember all of the empty links, they may or may not be complete OR links and files.

The goal wouldn’t be for you to track those links: `org-roam` would be handling them.  So, yes, the files would be created on an auto-save, but it wouldn’t be a problem if we implement a good cleanup function behind it.

> I don't find the lag of immediate file creation with `immediate-finish: t` that troublesome. It's not as ideal as simply typing `[[` and continuing on, but everything would be a proper OR link at all times. If I want to change `foo` to `bar` I just delete the link and insert a new one. This wouldn't require any changes to org-roam; just some customization of keys and a template

I also like this idea.  Note that I was just suggesting an implementation, not suggesting that this is something that I find particularly desirable.  I can see the value it would have for people using `evil`, but personally, I’m used to Emacs’s default paradigm for key-bindings.

> If the lag is really undesirable, a regex solution might be to do like org-ref `cite:` and then supply an org-roam function to create new files and replace results with proper OR links. Something like `roam:foo subject:roam` (to allow for spaces in note titles). Now there is no lag, a custom face can be applied to instances to make them stand out, they are easily edited until creation, and the file I'm working on can be saved willy nilly and only have OR create new auto-files when you want it to by invoking `M-x org-roam-create-from-regex` or something. It would also be possible to have this be a shortcut that either inserts an OR link if a file exists or returns the regex pattern if it doesn't

Not a fan of this idea.  Using `org` links and customising them in `org-roam` buffers (i.e. those visiting notes in your `org-roam-directory`) sounds like a better option

> In both of these solutions it will be possible to create many 'empty' OR files with just the single backlink to the org file I'm writing. If upon reflection I find I didn't really want `foo` I wanted `bar`, I now have an orphan `foo` file with no backlinks. However it's also possible that I may end up creating orphan files like these manually during normal OR usage anyway (calling `org-roam-insert` with a different template, then changing my mind later). I don't think it is really a question of whether they were automatically created (and tagged with `#+ROAM_AUTOCREATED: t`, unless someone really wants that tag). I just want to know if a file has content and/or links. These empty files, regardless of method of creation, can be found and deleted with the addition of another org-roam function or two, which can be manually invoked.

A house-cleaning function would be nice, yes, and I don’t think this should be run automatically either.  An interesting idea would be to implement an `org-roam-lint` which would behave similarly to `org-lint` to check file-metadata tags, orphan status, etc.

> 1. Add documentation for personally creating a shortcut (Roam `[[` or some other personal choice) to invoke either company-org-roam or a custom org-roam-insert template with `immediate-finish: t`. This wouldn't require any changes to OR's code.

As @jethrokuan suggested on Slack, we might use recommend using [keymap.el](https://www.emacswiki.org/emacs/key-chord.el).

> 2. Add a regex and custom face for `roam:possible new note:roam`, or something similar. This can also easily be a shortcut someone can implement to save themselves 5 s. Add a function to search an org file and replace these instances with auto-created OR files and links

As mentioned above, not a fan of that.

> In both cases above, I think it is sensible to also add manual org-roam functions to remove files that a) Have no content AND no links, and one for b) Have no links (or at least a list for user review, in cases where the content may be minimal or only some template defaults), regardless of whether they were auto-created or not.

See my comment above for the validity of wanting house-cleaning functions, and I think we should only be checking for links, not content.  Sometimes, a not is only useful for its back-refs, like the ones people use for general tags.

> Potential con to my proposal 2: Duplication of files. If a topic is referenced multiple times, OR will need to correctly create one file (or no files, if the topic actually exists already) and replace all instances with the correct link. I also suspect everyone would like auto-completion for existing regex instances to avoid misspellings (and possibly a similarity check to see if a user wants to merge very similarly named instances).

That’s another reason to use `org-roam-insert`, which would allow you to check which notes already exist, and adapt your notes accordingly.  The problem that I find with the automatic creation of links *without* prompting the user is that it seems to decrease the importance of making meaningful connections between your notes.

All in all, I think this is a discussion that we should all mull over for the moment.  Facilitating calls to `org-roam-insert` via `keychord.el` or even `yasnippet` is a good way to get the desired functionality with little to no effort required.  If a big project is to be undertaken in the next few weeks, I’d rather have it be the revamp of the side-window for listing backrefs.

**Comment by alan-carroll** [comment]
I like the idea of an `org-roam-lint`.

The idea of house-cleaning including content is to prevent deletion of notes with no backlinks (yet) but which I would still like to keep (something I captured with a template, but haven't integrated with other notes). If they have no content AND no backlinks, they're basically nothing anyway, but I might want to keep something _with content_ that doesn't have backlinks. Something with ONLY backlinks (general/index notes) would be untouched.
There are certainly ways for users to manage around this problem if content consideration is too much trouble. In that case I would simply want the documentation to be clear that all link-less notes will be removed.

The regex is just a suggestion to keep a frictionless workflow. I prefer using links and user-defined shortcuts, but then they will not behave like Roam and changing `[[foo]]` to `[[bar]]` would just be deletion of one link and insertion of another, which isn't what @mimischi was proposing (if I understand him correctly). Doing a little searching however it looks like it's possible to customize specific org-link faces, which would completely alleviate my concerns (though I think I would still want to be able to turn off the before-file-save hook and just call the function manually, if this issue ever progresses).

**Comment by zaeph** [comment]
> The idea of house-cleaning including content is to prevent deletion of notes with no backlinks (yet) but which I would still like to keep (something I captured with a template, but haven't integrated with other notes). If they have no content AND no backlinks, they're basically nothing anyway, but I might want to keep something _with content_ that doesn't have backlinks. Something with ONLY backlinks (general/index notes) would be untouched.

The goal of the linter would be to warn you of potential problems with your files, and to provide a way to fix them for you if you want.  I agree that it should check for content to prevent unwanted deletion.

> There are certainly ways for users to manage around this problem if content consideration is too much trouble. In that case I would simply want the documentation to be clear that all link-less notes will be removed.

Same as above: the user would be warned.  We’re working from the assumption that *nothing* gets deleted without user input.

> The regex is just a suggestion to keep a frictionless workflow. I prefer using links and user-defined shortcuts, but then they will not behave like Roam and changing `[[foo]]` to `[[bar]]` would just be deletion of one link and insertion of another, which isn't what @mimischi was proposing (if I understand him correctly). Doing a little searching however it looks like it's possible to customize specific org-link faces, which would completely alleviate my concerns (though I think I would still want to be able to turn off the before-file-save hook and just call the function manually, if this issue ever progresses).

We’ll see in the future.  I'll think more about this when I get the chance, but right now, I'm a little starved for time.

**Comment by jethrokuan** [comment]
This is somewhat resolved with work on fuzzy links.

**Comment by philippludwig** [comment]
Sadly a search for the word "fuzzy" in the org-roam manual does not yield any results, so here is how this seems to work:

1. In any org file, enter `[[roam:<title>]]`.
2. Go one char back
3. Press C-c C-o to open your new node.
4. Create new node as usual.
5. Go to the other node and remove the `roam:` from the link manually.

**Comment by AnweshGangula** [comment]
Looks like this is possible. nobiot talks about it in [this post](https://org-roam.discourse.group/t/how-to-to-get-title-of-the-target-note-working-with-inline-autocomplete-in-org-roam/782).
