### ISSUE TITLE
Have a visual way to retrace your steps in your `org-roam-directory`

### ISSUE THREAD

**Issue by zaeph** [org-roam/org-roam#531]
### Abstract
When you're having a *discussion* with your slip-box (your `org-roam-directory`), i.e. jumping around via links and backlinks to explore a line of thinking, you want to be able to easily retrace your step.  Right now, in `org-roam`, we offer backlinks in the `org-roam-buffer`, but there's no way to tell which of them brought us to the current file.  We need a visual way to retrace our steps through our `directory`. 

### Proposed Implementation
I see two levels of improvement, the latter being a stretch-goal for the long-term.

#### First level of improvement
- Implement a call-stack which stores which Org-roam buffers were visited.  Each item should be a `cons` of the format `(path . (current-buffer))` for solidity.
- Whenever we follow a link inside an Org-roam files, `setq-local` the current call-stack in the current buffer (unless it's `nil`), add it on top of the global call-stack, and `setq-local` the new call-stack in the new buffer.
- Add a face and a method for `org-roam-buffer` to highlight the previously-visited file (just as we do with `org-roam-link-current` in #516) which we might call `org-link-previous`
- Whenever we follow one of those `org-link-current`, `pop` the global call-stack to go back in the history, and do the same highlighting for that file.  If the buffer wasn't killed in the meantime, it should still have local call-stack, so use it for the highlighting.  If not, just copy the global call-stack.
- To handle buffer switches which weren't done via opening links inside Org-roam buffers, we need to handle two cases cases: 1) visiting a buffer or file already the call-stack, 2) visiting a buffer or file that isn't in the call-stack.  In 1), we just use the local call-stack to compute the relativity.  In 2), we `copy-list` the global call-stack, `pop` it until we find the buffer or file, and `setq-local` that variable.

This is a proof of concept, and it only handles a single line of history.  We could potentially use a more complex data structure with a list of call-stacks which would use `copy-list` to preserve the history, but it'd be quite complex, and by that point we'd be closer the toe second level of improvement.

#### Second level of improvement
Implement a tree à la `undo-tree` to visualise the different paths.
![undo](https://user-images.githubusercontent.com/12202828/80343986-1abfae00-8867-11ea-8ff1-af1a2e774f83.png)

#### Bonus round: Graphs
We could also do something similar with the graphs.

### Please check the following:
- [X] No similar feature requests

**Comment by zaeph** [comment]
I've thought some more about this, and I think I've reduced the complexity by identifying the two actions we want users to be able to do:
1. Users should be able to easily identify in the `org-roam-buffer` which of the backlinks will bring them back to the file on which they were before clicking a link in the current Org-roam buffer.  This can be done by creating an `org-roam-link-previous` as described above.
2. Users should be able to have access to their history s

In 1., the goal is not to have a global view of the history, just to know which link brought you here, so we can drop the global call-stack and only use `setq-local` to make the child aware of its parent.

In 2., it's about understanding the journey that your mind took through the notes, and that's where the global call-stack comes back.  The idea is to generate a buffer that would look like this:
```
Started at file1.
Moved to file2.
Moved to file3.
Moved back to file2.
Moved to file4.
-----
Started at file2.
Moved to file 4.
Moved back to file2.
```
The line would represent a break in the following of (back)links, which would happen if you opened a note via `org-roam-find-file`, for instance.  Now, imagine enabling this with a `org-roam-log-history` variable, and logging all this to an `*org-roam-history*` buffer, with all the files as links to their proper destination, and you have exactly what I wanted to implement with the second level of improvement, albeit not as visual.  However, we could easily beautify the output.

I'm really liking this idea, and I don't think it would be that hard to implement.  I'd love to hear your thoughts on this.

**Comment by zaeph** [comment]
Another idea: create an `org-roam-log-history-to-file` switch for logging everything into a `history.org` file which could live inside your `org-roam-directory`.  We'd have to exclude it from the cache and from the `org-roam-buffer` backlinks, but with timestamps, we would have a permanent log of the meanderings of our minds.

**Comment by zaeph** [comment]
This is linked to #118, although the scope isn't at large here.

**Comment by dit7ya** [comment]
A good implementation of this (though in the browser) is Andy Matuschak's working notes. 

For example, 
[this](https://notes.andymatuschak.org/z5uSCvx3W2GdzBVhWAAXrrCcykJ8SHimdJzg7?stackedNotes=z8RTzukqNLKFXzqLwx25HrUrg5E5jiziGznWB&stackedNotes=z2uXyfV67dnWLUKg1iDbsrHk3DGjtNWTxSTah&stackedNotes=z6Mx6PrJjGCf2akGM9pvoZ5Nk3EozcZcc9zHx&stackedNotes=z4Rrmh17vMBbauEGnFPTZSK3UmdsGExLRfZz1&stackedNotes=z2HUE4ABbQjUNjrNemvkTCsLa1LPDRuwh1tXC&stackedNotes=z3MzhvmesiD2htMaEFQJif7gJgyaHAQvKH49Z&stackedNotes=z7pGUpz2fQsHHUPbjThz85xXPvHwrmikAeYH4).

**Comment by JeffreyBenjaminBrown** [comment]
I think the simplest, most useful representation would be a tree, each vertex of which is a buffer, and each edge of which represents the "was visited from" relationship. This "navigation tree" does not capture the full traversal history, only the part that the user needs.

The navigation tree could look like an ordinary org file, each headline of which represents a buffer. Each top-level headline is a buffer containing a file that the user found using `org-roam-find-file` or (less commonly) `find-file`. Every child headline is a buffer containing a file that was visited via a link in its parent -- whether it was already open or not. When a user switches buffers using any other method, and in particular when a user returns from a child to its parent, that information is not recorded.

Suppose, for instance, that a user visits a file P, and then follows a link in P to a file C1, and then returns to P, and then follows a link to another file C2. The fact that the user returned to P is not recorded (because how would the user even use that information?). The user would therefore end up with a buffer like this:

```
* P
** C1
** C2
```

If a buffer is closed, each of its children that remains open is promoted to the top level.

From the view-tree, the user can visit buffers; fold, cut, copy and paste subtrees; and insert new leaves. Thus the navigation tree does not have to perfectly represent the user's history (although it probably usually will); the user can tailor it to optimize their navigation experience. 

Users are likely to want to save the navigation tree, and use one to launch a new session. And they might want to be able to create headlines in the tree that don't link to any buffer, but are merely used to group subtrees.

**Comment by jcguu95** [comment]
In short, I think reading notes in org-roam should not be harder than reading wikipedia. That is, we need at least

1. a way to jump back and forth in the history line, perhaps even better
2. a way to easily open and close many tabs

**Comment by JeffreyBenjaminBrown** [comment]
@jcguu95, there are already decent ways to get your second wish. To easily close many tabs, there's the buffer buffer `(C-x C-b)`. The shortcut for opening a new tab without visiting it is a little more complex than in the browser (in most of which you just shift-click); it's
```
C-c C-o
C-x 4 0
```

You could bind a macro to make it fewer keystrokes -- maybe `C-c n o`, for "open without viewing", which would maintain parallelism with the existing org-mode shortcuts if your setup is like the default.

Buffer mode doesn't show you your history, just a queue of buffers, so it doesn't grant your first wish.

**Comment by zaeph** [comment]
I'd still very much like to implement this feature, but this is still low priority.  I'm scheduling it for after 1.3.

**Comment by jethrokuan** [comment]
Not within the scope of Org-roam anymore, feel free to implement outside.
