### ISSUE TITLE
Org-roam needs a logo!

### ISSUE THREAD

**Issue by jethrokuan** [org-roam/org-roam#533]
### Brief Abstract
We need a logo for this project.

### Long Description

While setting up some other misc admin things, it dawned upon me that we need a distinct, recognizable logo. Could be just text, could be something fancy. I'm poor at design, but if there's anyone who wants to take a stab at it, please do so!

**Comment by zaeph** [comment]
I might be able to tackle this.

I've designed the logo for [`ranger`](https://github.com/ranger/ranger) (it's still a WIP), and I've done a quick one for [`org-roam-bibtex`](https://github.com/zaeph/org-roam-bibtex).

<img src="https://ranger.github.io/ranger_logo.png" width="150"> <img src="https://raw.githubusercontent.com/zaeph/org-roam-bibtex/master/doc/logo-r500.png" width="120">

However, it takes me ages to design something, so I'll have to think about this next week!

**Comment by dit7ya** [comment]
The ranger one has a clever reference to Vi, I would love to see something similar with the org unicorn (a more modern redesign of it).

**Comment by zaeph** [comment]
I'm back a little earier than I anticipated.  Turns out designing a logo is a pretty good way to delay the writing of one's thesis.

> The ranger one has a clever reference to Vi…

It is indeed.

> …I would love to see something similar with the **org unicorn** (a more modern redesign of it).  [emphasis added]

\**drum-roll*\*

<img src="https://user-images.githubusercontent.com/12202828/80516724-2f459880-8984-11ea-8312-580159f492f3.png" width="150">

Obviously, it's just a prototype, but I think it came out pretty all right.  There are some visual oddities going on with the unicorn, but other than that, it's pretty smooth.

Let me know what you think!

**Comment by ocharles** [comment]
I think it's a beautiful logo, but unfortunately to me it looks more like a logo for org-mode itself, rather than org-roam in particular

**Comment by zaeph** [comment]
> I think it's a beautiful logo, but unfortunately to me **it looks more like a logo for org-mode itself, rather than org-roam in particular**  [emphasis added]

You're absolutely right.  So, I went back to the drawing board with the assumption that the unicorn was enough to represent Org-mode, and that I could focus on Roam instead.

Here's the result:
<img src="https://user-images.githubusercontent.com/12202828/80527155-35437580-8994-11ea-9837-65a2caa5bec3.png" width="150">

I also went ahead and addressed a number of the visual snags that bothered me with the earlier iterations.

**Comment by ocharles** [comment]
Now we're talkin'!

**Comment by zaeph** [comment]
Some minor visual improvements:
<img src="https://user-images.githubusercontent.com/12202828/80533396-d2ef7280-899d-11ea-9e0f-d44e4fffc985.png" width="150">

**Comment by zaeph** [comment]
And a colour change that changes everything:
<img src="https://user-images.githubusercontent.com/12202828/80534314-5198df80-899f-11ea-8e92-fc07b970f46d.png" width="150">

**Comment by zaeph** [comment]
And a bonus round with extra colours (since we're dealing with unicorns, here):
<img src="https://user-images.githubusercontent.com/12202828/80536325-7fcbee80-89a2-11ea-9667-90d045ecb835.png" width="150">

**Comment by jethrokuan** [comment]
They all look lovely! Although I think the below appeals to me most.

![image](https://user-images.githubusercontent.com/1667473/80561490-3964a700-8a17-11ea-94dd-8997cb96d8b4.png) 

@zaeph let's use this to kickstart the discussion on Discourse.

**Comment by dit7ya** [comment]
I have a worry that someday RoamResearch will trademark the word Roam. Even if they don't, looking at the big 'ROAM' it feels like we are just mimicking them. I also had qualms about the name of this project since the beginning. 

Point is, Roam is just an instance of <PKM tools that provide easy bidirectional linking and several nice features> and we don't have to reference them to mean we are also providing such features. I wish there was a general enough term for it. 

I also understand that now org-roam has already become quite a known thing and changing the name suddenly might have some costs.

Sorry for the long wall of text, was just thinking out aloud. 

Apart from the word ROAM I absolutely love these logos.

**Comment by zaeph** [comment]
> They all look lovely! Although I think the below appeals to me most.
> 
> <img src="https://user-images.githubusercontent.com/12202828/80534314-5198df80-899f-11ea-8e92-fc07b970f46d.png" width="150">

Glad you like it!  The rainbow looks great, but I agree that it's a little too much.  I'm sure we'll be able to think of some place where the rainbow-unicorn is warranted. :)

Also, I hope you don't mind, but I'd like to release the logo under CC-BY-SA.  With graphic design, I like to associate my name to the work I do so that I can create a portfolio.  It also helps people find me if they want to work on a project!

> @zaeph let's use this to kickstart the discussion on Discourse.

*Yes*, that'd be lovely!

-----

> I have a worry that someday RoamResearch will trademark the word Roam. **Even if they don't, looking at the big 'ROAM' it feels like we are just mimicking them**. I also had qualms about the name of this project since the beginning.
> Point is, Roam is just an instance of and we don't have to reference them to mean we are also providing such features. **I wish there was a general enough term for it.**  [emphasis added]

I agree that this could be an issue in the future.  However, to quell your worries, adapting the logo now that it is designed would not take me long, so if they were to do that, the logo would be the least of our worries.

For your second point, I also love the word *roam*.  It's short, sweet, and quite euphonic to my ears.  However, we weren't the first on that wagon, and as sucky as trademark laws are, there isn't much we can do about it.

If a safety-rename is to be considered—and, FYI, I think it would be warranted—it should be done relatively soon, now that our medium-sized user-base is still manageable (and thanks for the *1'000 stars*, by the way !)

All right, let's explore options.  Give me a minute to fetch my *English Literature & Linguistics* hat. 🎓
(I don't get to do that often in the world of software development !)

*Roam* is quite euphonic to my ears because of the nice /əʊ/-diphthong—i.e, the vowel glide represented by the grapheme 'oa'—but also because it is ended by the nasal sound /m/, which gives it a very soft landing.  If we need to find another name, we might as well stick to that phonological structure to echo the idea in a non-trademark-infringing way.

Also, we might want to keep it semantically close to the meaning of *roam*.

A candidate that I particularly like is the word *rove*.  Phonologically, it has the benefit of being a minimal pair with *roam*—i.e., there's just one phoneme (= logical unit of sound) that changes between the two, compare /rəʊ**m**/ vs. /rəʊ**v**/.  An added benefit is that, to say *Org-rove* out loud, you'd have to say *grove* as well, which is a lovely pastoral term for a small group of trees.

For some ideas, [here's an excerpt of the entry for *roam* in the Oxford Thesaurus of English (1st ed.)](https://zaeph.tk/files/dev/roam.html).  I've hosted it on my server for better HTML highlighting, but I've selected a few passages below:

> **Synonyms**:
>
> […]
> 
> **ROAM**, **rove**, range, knock about / around, drift, coast, gallivant, gad about, prowl, mill about; trek, trudge, stretch one's legs;
> 
> […]
> 
> **AWKWARD SYNONYMS**
>
> wander; roam; rove; range; stray
>
> These words all denote walking or moving in some way that is not a direct line. Some imply more energy and pupose than others.
>
> […]
> 
> Those who roam move around with little forward planning, but generally show more energy than the wanderer: packs of savage dogs roamed the streets | dark lanes where gangs roamed.
>
> **Rove is a rather old-fashioned word meaning ‘travel constantly without a fixed long-term destination’ (a roving busload of activists who went all over Europe | communication with a roving agent was always fraught with difficulties), as did the rovers who were sea pirates in earlier centuries.**
>
> **Range** is a less common word, indicating movement that is free from restrictions or constraints and is usually over a wide area: railway entrepreneurs ranged the globe in search of trade | they ranged over the Pacific in outriggers.
>
> **Stray** denotes movement away from where one should be (if you stray off the route it's almost impossible to get back | for an instant her tired mind strayed), or into a wrong or inappropriate place (a hawker of ladies' underwear who had accidentally strayed into a monastery).

Also, just to show you how trivial it'd be to change the name, here's a prototype with *rove*:
<img src="https://user-images.githubusercontent.com/12202828/80569747-dadd0000-89f9-11ea-9ac6-db231430ced9.png" width="150">

-----

> I also understand that now org-roam has already become quite a known thing and changing the name suddenly might have some costs.

I don't think it would be that much of a problem.  We're still early in the journey, and publicising it wouldn't prove too difficult.  Sure, there'd be minor inconveniences with MELPA, repository-clones, and other packages which have already done some work with it, but nothing that a handful of regexps and issues filed on their trackers wouldn't solve.

> Sorry for the long wall of text, was just thinking out aloud.

Oh boy, if your answer was long, and I don't know what mine qualifies as.

> Apart from the word ROAM I absolutely love these logos.

Thank you!

**Comment by jethrokuan** [comment]
I'm not too worried about the name. Afaik the Roam Research people are aware of the project, and have no issues with the name (as of now). We can always change the name later, if it becomes a real issue.

**Comment by alanz** [comment]
> I'm not too worried about the name. Afaik the Roam Research people are aware of the project, and have no issues with the name (as of now). We can always change the name later, if it becomes a real issue.

Perhaps just ask them?  Or is it a case of "don't ask, don't tell".

**Comment by progfolio** [comment]
Another concept for a logo would be something that evokes the image of a graph

**Comment by ocharles** [comment]
I could imagine a slipbox could make for a good logo, depending on how Zettelkasten we want to be

**Comment by jethrokuan** [comment]
This issue has been mentioned on **Org-roam**. There might be relevant details there:

https://org-roam.discourse.group/t/org-roams-logo/15/1

**Comment by asymmetric** [comment]
@jethrokuan does org-roam have a Discourse?

FWIW, I think the rainbow vesion is extremely nice and wins :)

**Comment by jethrokuan** [comment]
@asymmetric we're still in the midst of setting it up!

**Comment by codygman** [comment]
Is this finalized or still open for submissions?

**Comment by zaeph** [comment]
> Is this finalized or still open for submissions?

Nope, still open, and you're welcome to submit something.

**Comment by progfolio** [comment]
Relevant discourse discussion: https://org-roam.discourse.group/t/org-roams-logo/15/13

**Comment by jcguu95** [comment]
What a delightful thread :D :D :D

**Comment by junwei-wang** [comment]
What a nice logo. I know nothing about designing a lot. 
My question is which tool are you using and could you please share the open the source?
