### ISSUE TITLE
Database access error from syncing notes

### ISSUE THREAD

**Issue by resttime** [org-roam/org-roam#550]
# Description
Hi, I've been trying out org-roam and it's pretty cool. I believe I've run into an error due to sharing the notes between two computers synchronizing with syncthing (probably will be the same with Dropbox).

The cache can't update and an error gets returned when trying saving changes to a note: `Database access error: "attempt to write a readonly database"`
#### Steps to Reproduce
1. Open a note on one computer makes some changes then save.
2. Open a note on the other computer. make some changes then save.
3. Go back to first computer and try save new changes.

#### Expected Results
org-roam cache updates properly

#### Actual Results
`Database access error: "attempt to write a readonly database"`

### Versions
- Emacs (`C-h v emacs-version`): v26.3
- Org-roam commit: 0132546e56eb5cffd6cc52177b6ffbeab0d84743

![image](https://user-images.githubusercontent.com/2598904/80854650-d38b4180-8c07-11ea-822b-b184865283a1.png)

**Comment by alan-carroll** [comment]
Are you closing emacs sessions between switching computers?

These two posts may also be relevant:
https://techblog.dorogin.com/sqlite-error-8-attempt-to-write-a-readonly-database-62b80cc6c9db
https://stackoverflow.com/questions/3319112/sqlite-error-attempt-to-write-a-readonly-database-during-insert/3319163#3319163

Sounds like it is likely a sqlite issue, or specific to syncthing. An answer for a calibre problem with syncthing says not to open sqlite db's in two places with it:
https://forum.syncthing.net/t/using-syncthing-with-calibre-safely/12662

Have you tried using Dropbox with the same error, or just anticipate it?

**Comment by resttime** [comment]
The problem is anticipated with Dropbox just by a weak association. After sifting through the links I think you're right that it might be a limitation of sqlite and/or syncthing. Sessions are left open on both so closing them to not open the db in two places definitely works.

I'm just curious that if detectable, if it'd be possible to "repair" the connection by automatically reconnecting since restarting emacs does the trick too. I'm satisfied with the solution though. I'll let the maintainers decide whether it's worth trying to dig deeper or close the issue.

Thanks for your help!

**Comment by zaeph** [comment]
An idea might be to create an option to use different db per hotstname (retrieved via `(system-name)` in Emacs).  I'm not sure if we'd need to run cond-checks to keep the db updated when switching to another machine, but if we do, we could just store the state of sisters in the db, check if there has been any change since the last modification, and update the db on the first insertion/retrieval to it.

**Comment by jethrokuan** [comment]
What I do is I keep the database outside my Dropbox directory. You may do so by setting `org-roam-db-location`. This problem is particularly problematic for me, since I use Emacs as my entire desktop, so shutting it down is equivalent to shutting down Emacs.

On the other hand, if you shut down Emacs gracefully, the sqlite database is always closed gracefully. Then if you give time for Dropbox to sync the database, you shouldn't see this issue.

**Comment by TimQuelch** [comment]
Another solution for Syncthing is to simply not sync the org-roam database so it is generated locally on each machine. You can do this by adding org-roam.db to the .stignore file (https://docs.syncthing.net/users/ignoring.html). Not sure if there is an equivalent for dropbox

This also allows you to store your roam directory at different absolute paths on each machine
