### ISSUE TITLE
?types/properties for edges and nodes

### ISSUE THREAD

**Issue by bijang** [org-roam/org-roam#627]
Would it be possible to have the facility to add signifiers to the links between nodes, the 'edges', and o the nodes themselves? in whatever format is desired by the user eg la label, a symbol or a letter or a colour change etc, so that these symbols and their associated links/connections, can be given a meaning; 
this meaning would be predefined by the user to whatever they want the particular alteration to signify for the purpose. 
In this way can have the option to turn knowledge graphs or concept maps into more meaningful ontological maps, for whatever purpose eg argument maps, logic maps, etc. This would not mean an alteration to the program as it stands or a set of predefined symbols etc, but just the option to add a self defined meaning in whatever fashion, to certain links if it were desired for a particular circumstance

**Comment by zaeph** [comment]
It's not something that is advocated in the slip-box method as described in Ahrens (2017), but I see how it could be valuable.

Technically, it could be done by appending something to the link which would specify the type of relation, but as it stands, you can do it in a verbose fashion by specifying in the context (i.e. the paragraph in which the link was found) what type of link it is.

**Comment by bijang** [comment]
thanks for the quick reply! that's fair enough, I respect the slip box method, it might be useful in certain areas like you say, it occured to me I thought I had seen roam do a kind of implementation of this that looked interesting and simple, where they used a double colon, preceeding the label, as syntax for the type/property, of the edge/node. Though the benefit of it is probably really reaped in the visualisation, so not sure how this would tranlate to a graphviz representation.

**Comment by zaeph** [comment]
I think it wouldn't be hard to implement as far as the text is concerned, but I'm not sure if the graphical backends would support them too well.  [Some of the options which are explored on Dicourse](https://org-roam.discourse.group/c/dev/graph) rely on links having the same meaning, which would make it difficult to implement relationships with qualifiers.

More generally, I think the beauty of the method is in the freedom allowed by only having nodes and links where the latter do not require any other definition than 'is related to'.  You're then free to associate nodes to your heart's content without having to specify exactly what the relation was.

**Comment by bijang** [comment]
I agree, I think the freedom would come with the option of modifying this very open/minimal definition, as a starting point good for most occasions, if there was an option to label with text or even a self defined symbol, that would be cool, if you felt it appropriate. BTW thanks for your work on this project

**Comment by alan-carroll** [comment]
The Roam usage creates an attribute. I think it is hard to plan how to emulate this _**exactly**_ because Roam has yet to fully lay out what the functionality of attributes will be in the future.

I've wanted this ability to assign 'relationship types' to links also. I had been planning on iterating through some hacky solutions that would solve my personal use cases without interfering in org-roam generally.

But honestly with #592 it might be fairly easy to add a similar syntax and do something like add 'types', 'tags', or 'relationships' on to links, though. It would require a small database schema modification and a little bit of extra syntax parsing, and then adding a tag to a link (and getting completion based on existing 'link-tags/types') could be done. The primary issue I see with that implementation is integrating `file:` link compatibility. It could be done, I'm sure, though.

I'll try putting a prototype together.

**Comment by jethrokuan** [comment]
> I've wanted this ability to assign 'relationship types' to links also.

Org-brain does this, and it's something that I could never get used to. My main gripe is that it had significantly increased the friction for me to link things.

**Comment by alan-carroll** [comment]
@jethrokuan I've never dug into org-brain, but I probably should just to see what has already been done.

Is it their use of 'parent', 'sibling', 'child'? If so, I don't mean relationships in that way. I mean it in the sense that a graph's edges can be given additional context for how I am linking a note, which could be exploited later to re-surface particular notes when I want them, or create particular views over a set of notes that otherwise don't share links.

In my mind the regular link is the default modus operandi, but you would very intentionally 'tag' a link when you wanted to add something the link itself doesn't convey. The tag replaces other schemes such as subdirs, filename/title conventions, or having to write context around a link, among others.

**Comment by bdarcus** [comment]
Not prompted by this in particular, but I think it would really help to have two things to discuss these sorts of requests:

1. use cases or user stories; not "x would be cool" but rather "here's a concrete example or two that prompts this request."
2. some kind of grounding in the theory underlying the software; not graph theory, but zettelkasten.  The reason is because it's well-developed, over a number of decades, and there's different communities of people (most notably recently at zettelkasten.de) that have thought through pretty much anything that would be proposed here, in the context of figuring out how it should work in software. Not easy to search for this topic over there, but [here's a post](https://forum.zettelkasten.de/discussion/comment/4318/#Comment_4318) that may be worth thinking about?

**Comment by bijang** [comment]
I agree with everyone here! 
Seems to me it boils down to whether you want this to be a strict implementation of some form of the current Zettelkasten 'theory'.
it's an interesting discussion, apologies for my loose language and inappropriate colloquialisms earlier, 
first of all it mainly occured to me because this is what can be done in roam; whether that fits in with the current reading on zettelkatsen theory, or model lets say, I'm not sure truly matters, unless the objective of this project is to be nothing more than that. 
However, if it were that the proposed functionality is optional, not a mandatory step in workflow, and were felt that this program could flexibly incorporate options to make it more than just an excellent zettelkasten implementation, this shouldn't be an issue. 
Extraneous steps or complicaitons to the workflow should certainly not be introduced, I agree with @jethrokuan there entirely, there should be no friction so to speak. 

The question as I see it, is whether optional, non-intrusive functionality, introduced alongside the 'zettelkasten model', that isn't in-line with said model and may then turn this into something other than what was designed by that well-developed theory, is acceptable or not.

my opinion, whatever is decided will be the right choice because this is a fantastic system and can't go wrong! 
also, whatever is decided, there's no stopping people expanding programs in emacs and org to be more flexible and do more than what they were intended for or envisioned as; if there's a true demand for the above it'll materialise in some fashion or other I'm certain. (unfortunately I have zero programming skills, I'm a doctor by trade and it's something I lament isn't taught to us at any stage..., though maybe I'll learn one day so I can be more useful to you here) 
[Perhaps a prototype might not be a bad idea @alan-carroll ]

**Comment by bdarcus** [comment]
> The question as I see it, is whether optional, non-intrusive functionality, introduced alongside the 'zettelkasten model', that isn't in-line with said model and may then turn this into something other than what was designed by that well-developed theory, is acceptable or not.

For me personally (I don't contribute code though): yes.

If you read how I wrote that bit, I don't think I was suggesting it be thought of as a straight-jacket; only that it provides some foundational principles, and a common language, that makes it easier to assess new requests.

**Comment by alan-carroll** [comment]
I'm making some progress on a proof-of-concept prototype. When done I'll try and aggregate some material on specific use-cases and/or zettelkasten integration, make a couple demo gifs and post on the discourse.

**Comment by alan-carroll** [comment]
[Posted a prototype](https://org-roam.discourse.group/t/add-link-tags-feature/171) with a looong motivation section @bdarcus 😉 Demo at the bottom.

**Comment by Kungsgeten** [comment]
@alan-carroll `org-brain` lets you add custom edge annotations between relationship links, not only the defined types of relationships. You could have a look at https://github.com/swhalemwo/obvz which shows an example with edge annotations. `obvz` is a separate package/program which uses `org-brain`.

**Comment by qlibp** [comment]
still wonder whether or not this feature would be implemented by org-roam

best

**Comment by jethrokuan** [comment]
Org-roam will not implement this, as this is not something the default link-types support.
