### ISSUE TITLE
Two different locations for manual; README.md only lists one

### ISSUE THREAD

**Issue by jgoerzen** [org-roam/org-roam#692]
README.md links to https://org-roam.github.io/org-roam/manual/ and promises that it includes Doom and Spacemacs information.  It doesn't.  However, the manual at https://org-roam.readthedocs.io does.  It's unclear to me the relationship between these two manuals, but perhaps a link to the readthedocs one should be added?

**Comment by progfolio** [comment]
We're in the process of improving the documentation. The Info manual provided with Emacs (accessible via `M-x info`) which is mirrored at https://org-roam.github.io/org-roam/manual/ is more current.

I believe the readthedocs has been deprecated in favor of those.
Is that correct, @jethrokuan?

For now as far as Spacemacs, Doom and Windows installations go, you can follow the readthedocs instructions. If you have any problems please let us know. We will take care of consolidating the documentation so that it is easier to use.

Related: #690

**Comment by jethrokuan** [comment]
Yes, the readthedocs documentation is no longer being updated, as it builds from master branch and that fails now. We're no longer officially pointing to the readthedocs site. I'm in the process of slowly migrating the documentation over, hopefully the situation will be better in a few weeks.

**Comment by skangas** [comment]
Thanks for providing info documentation, this is highly appreciated.

**Comment by jethrokuan** [comment]
Most of the information has been ported, but the documentation is still somewhat lacking. We hope to address this in 1.2.2.

#830
