### ISSUE TITLE
Cryptic error message on bad files

### ISSUE THREAD

**Issue by jethrokuan** [org-roam/org-roam#728]
### Description
Files with malformed roam properties can cause database builds to fail and halt the use of Org-roam. On this scenario, we should warn, and return nothing, rather than halt all operations.

#### Steps to Reproduce

Create a test org file:

```
#+TITLE: Test
#+ROAM_TAGS: "hello
```

On `org-roam-db-build-cache`, we'll see `org-babel-read: End of file during parsing` in the Messages buffer, and not much else.

#### Expected Results

Most of rest of Org-roam functions normally.

### Environment
- Emacs: GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0)
- Framework: Doom
- Org: Org mode version 9.4 (nil @ /home/jethro/.emacs.d/.local/straight/build/org-mode/)
- Org-roam: 1.1.1

**Comment by d12frosted** [comment]
Haha, I also just faced this issue. Is there a way find an offending file?

**Comment by progfolio** [comment]
The root of the problem with tag parsing is in `org-roam-str--to-list`. Malformed values choke at this assignment:

```emacs-lisp
               (alist (org-babel-parse-header-arguments (format format-str str-elem)))
```
This should be addressed so that we are more forgiving when parsing tags, but that's a separate issue.

org-roam-doctor should fail more gracefully and let the user know:
- the checker that failed
- the error thrown
- the file it was thrown in
- the value that caused the error to throw

This would help the user narrow down the error and, if nothing else,  allow for better issue reports.
This should be implemented, and then the user-error here should recommend running `org-roam-doctor` in addition to the current message.
