### ISSUE TITLE
Bury the distinction between links and the headline-subheadline relationship

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [org-roam/org-roam#824]
(This proposal regards a change in how the user views the data. There would be no change to how the data is represented.)

The distinction between headlines and links might be sharper than necessary. It surely belongs under the hood, but it would be cool if it weren't so visible to the user.

Every org-headline can be thought of as bearing a relationship with its parent headline. Under the hood, the headline-subheadline relationship and the linked-to-linked-from relationship are treated differently -- and they should be. Org-roam doesn't give an ID to a headline until the user wants to connect something other than its parent to that headline. That is both cpu- and memory-efficient. If every headline had an ID, most of them would go unused, and indexing would be slower.

But maybe that distinction does not need to be such a defining part of the user experience.

In org-mode you can unfold the contents of a heading, or not. In org-roam, it would be natural if you could similarly unfold the content of a link, without switching buffers.

In that case, the user could explore a few generations of links (a few layers deep in the tree of links) without getting lost. They could also "look backward" from a headline, to see not just its parent headline, but also all the other things that link to it.

**Comment by zaeph** [comment]
It's on the roadmap to have `id:`-links show their hierarchy in the `org-roam-buffer`.  This is easily achievable by retrieving all the parent headlines and the filename, and storing it in a new row within the db.  It's easy to do, but we need to think of a way to make it look good, which is why I'm linking this to the revamp.

As for ID-proliferation, this method also has the advantage of only creating ID for the relevant headlines.  In the future, unreferenced headlines might have their ID removed by `org-roam-doctor`.

**Comment by JeffreyBenjaminBrown** [comment]
> It's on the roadmap 

Can the roadmap be found online?

> to have id:-links show their hierarchy in the org-roam-buffer.

That will be nice :)

But (and please forgive me if this is obvious) the change you describe maintains a hard distinction in the user's experience between links and the heading-subheading relationship. This proposal's aim is to unify those two experiences. If it were implemented, the roam-buffer would no longer be necessary.

**Comment by zaeph** [comment]
I've re-read your original request, and the problem with it is that it requires transclusions, i.e., the inclusions of other files into another file whilst maintaining editing capabilities.  There is no reliable way to do this in Emacs at the moment, and it's too stark a departure from notes'n'links.  At this point, it feels like massive overengineering.

I'd much rather sink time into making the side-buffer as informative as possible which is something that is clearly within the realm of possibilities.

**Comment by JeffreyBenjaminBrown** [comment]
I thought that might be the case. Maybe one of these years, then. Thanks for your work. This project is awesome.

**Comment by zaeph** [comment]
> Can the roadmap be found online?

I forgot to address this point.  It's not online because it doesn't actually exist.  It's more of a sense of direction based on what Jethro and I are reading here, and we try to leverage our time by prioritising what feels more beneficial for the package.  I'm keeping tabs on those ideas in my Org-mode setup for the internal stuff, but mostly, you can follow the different paths on the tracker based on labels and priorities.

**Comment by zaeph** [comment]
I've decided to make the _roadmap_ a little more visible, so I'm going to be using the [Milestones](https://github.com/org-roam/org-roam/milestones) to reflect it.

**Comment by jcjolley** [comment]
Here is some previous work on transclusion that could partially solve this problem.  It only supports going one layer deep, but it's a potential starting point: https://github.com/whacked/transclusion-minor-mode
