### ISSUE TITLE
Add support for other link types to headings

### ISSUE THREAD

**Issue by spacekitteh** [org-roam/org-roam#827]
### Brief Abstract
I wish to integrate org-roam with org-brain; my existing notes are riddled with `brain:`, `brain-parent:`, `brain-friend:`, `brain-child:` links which are basically just `id:` links.

### Proposed Implementation (if any)
There should be an `defcustom`'d alist for link types, mapping from link types to extraction functions.

**Comment by zaeph** [comment]
The problem is that the extraction function is not modular:
https://github.com/org-roam/org-roam/blob/87403b330ce713a892e3e35ff4174a8e2727e24d/org-roam.el#L496-L554

It would be possible to make it so, and to then have a variable which would map link-types to extraction-function, but in your case, wouldn't it be simpler to rename those properties to :ID:?  The links in Org-brain do not work in vanilla Org-mode, and it might be the opportunity for you to port them to something a little more reliable.

**Comment by spacekitteh** [comment]
They -are- `:ID:`. It's the -link- format which what I described, i.e. `[[brain-parent:<org-id>][desc]]`.

**Comment by spacekitteh** [comment]
And

> The links in Org-brain do not work in vanilla Org-mode, and it might be the opportunity for you to port them to something a little more reliable.

The links encode semantic content.

**Comment by zaeph** [comment]
I understood you the first time, but I maintain that the links are not functional in base Org-mode.  Even if they include semantic content within Org-brain, I'm sure there'd be plenty more to interface properly with Org-brain, and since the two packages seem to be achieving a goal that is similar, facilitating their connection seems a little superfluous.

So, I'll reiterate: I don't see this as a pressing issue, but feel free to PR.

**Comment by jethrokuan** [comment]
I'm going to start caching all links detected by org, so org-brain's links will be picked up. But displaying them will require the side buffer revamp.

**Comment by spacekitteh** [comment]
What would be required to get this to work?

**Comment by jethrokuan** [comment]
All links are now cached by Org-roam v2.
