### ISSUE TITLE
Headline-link UX (basic)

### ISSUE THREAD

**Issue by zaeph** [org-roam/org-roam#831]
Now that #783 has been merged, I want to work on basic UX for inserting links to headline.  I'm thinking of a two-step completion where we first choose the file, then the heading.  UX-wise, I'm thinking of an `C-u` argument for `org-roam-insert` and `org-roam-find-file` which would allow us to do that, but the problem is that it assumes that users will know whether they want to go to a headline before they run the command.

Implementing actions à la `helm`/`ivy` would be the best way to handle this, but we'd still need to support `ido` to maintain compatibility.  Therefore, I'm thinking of dropping the `C-u` argument idea in favour of always going for a two-step completion with the basic completion engine, and potentially even with `helm`/`ivy`.  The difference would be that, with the latter, you'd be able to run an action to link straight to the file.

I have to think some more about this, but I'll get started on it this week.

Related to #592.

**Comment by yuchen-lea** [comment]
My current workflow is:
1.  `helm-org-agenda-files-headings` to find candidate function
2.  select one or mark multiple healines
3. call insert link functions
4. if nothing found, create a new note using capture template, implementation like this [this](https://github.com/emacs-helm/helm/issues/1806)

Sometimes, I would call `helm-org-rifle-agenda-files` instead, which excecutes a full text search within the headline content rather than headline title only.

As for me, the ideal workflow may be:
- search in headline and file title
   - **a** if found, mark and insert headline id link
   - **b** if not found, you can chose:
       - do a full text search
           - if found, same as **a**
           - if not found, create new note
       - create new note

**Comment by spacekitteh** [comment]
Would a `capf` for headings known by `org-id` help at all with this?

**Comment by zaeph** [comment]
#1105 removed the quick `[[foo]]` syntax in favour of `[[roam:foo]]` in order to play well with other parts of org-mode.

The key problem with this issue is that we have two paradigms at odds:
1) A traditional command which drops you in a completion engine which.  Upon selection, the candidate is processed into a functional link.  If the user wants to edit the link, there is no convenient way to do so (maybe we could co-opt one of `org-roam-doctor`'s function?)
2) A context-sensitive command which relies on at-location completion with `company-mode`.  Upon selection, the candidate is *not* processed to allow editing.

As I've mentioned in #1105, 2) isn't a hill worth dying on for me right now.  1) is closer to the Emacsian paradigm, and as such, I'd rather work on a feature-complete UX for 1) before moving on to 2).

I'll be working on this in the coming weeks.
