### ISSUE TITLE
Option to store metadata for encrypted files after exit

### ISSUE THREAD

**Issue by oakrc** [org-roam/org-roam#835]
### Brief Abstract
Have an option to store metadata for encrypted files after exit

### Long Description
org-roam removes the metadata for encrypted files from the database after exiting Emacs. Could we have an option to store the metadata after exit so that an user can search titles (instead of `filename.org.gpg`) without rebuilding cache? I am new to Emacs and I couldn't find the function that controls the behavior. 

### Proposed Implementation (if any)
```lisp
; Cache metadata for plain-text files only (default)
(setq org-roam-db-metadata 'plaintext-only)
; Cache metadata for both plain-text and encrypted Org files
(setq org-roam-db-metadata 'all)
```

### Please check the following:

- [X] No similar feature requests

#528 might be relevant

**Comment by zaeph** [comment]
The problem is that storing the titles in the db would leak them in the db.  I haven't had a look at our cond-tree for encrypted files, but I think it's going to be complicated to do it reliably without parsing all the files on init.  We might be better off encrypting the whole db.

I'll think about it, but just as #528, this is fairly low-priority compared to the other UX elements that we need to address.
