### ISSUE TITLE
There are no backlinks when org-roam-directory is an app document directory in iCloud.

### ISSUE THREAD

**Issue by fountainer** [org-roam/org-roam#869]
### Description

I used [this configuration](https://org-roam.readthedocs.io/en/master/installation/) for spacemacs. There are no backlinks when `org-roam-directory` is an app document directory in iCloud. For example,

```emacs-lisp
(setq org-roam-directory "/Users/sfq/Library/Mobile Documents/iCloud~com~coderforart~iOS~MWeb/Documents/roam/")
```

#### Steps to Reproduce

1. Run `org-roam-find-file`, Input `foo`.
2. In the `foo` buffer,  run `org-roam-insert`, input `bar`.
3. In the `bar` buffer, run `org-roam`, showing "no backlinks".

#### Backtrace

No errors.

#### Expected Results

Showing backlinks in `*org-roam*` buffer.
#### Actual Results

No backlinks in `*org-roam*` buffer.
### Environment

- Emacs: GNU Emacs 27.0.91 (build 1, x86_64-apple-darwin19.4.0, Carbon Version 162 AppKit 1894.4)
 of 2020-05-08
- Framework: Spacemacs
- Org: Org mode version 9.3.6 (9.3.6-17-g389288-elpaplus @ /Users/sfq/.emacs.d/elpa/develop/org-plus-contrib-20200224/)
- Org-roam: 1.2.0
### It works when `org-roam-directory` has other values.

It works when  `org-roam-directory` has other values, e.g., `~/roam/`, ` /Users/sfq/Library/Mobile Documents/com~apple~CloudDocs/roam/`. It seems that `org-roam-directory` cannot be the directory of an app document (e.g., `MWeb`) in iCloud.

Screenshot when it doesn't work. `org-roam-directory` is `/Users/sfq/Library/Mobile Documents/iCloud~com~coderforart~iOS~MWeb/Documents/roam/`.
<img width="655" alt="Screen Shot 2020-06-27 at 11 12 35 AM" src="https://user-images.githubusercontent.com/5546074/85914074-b02ded00-b86c-11ea-9f47-edbba420f1ab.png">

Screenshot when it works.  `org-roam-directory` is `/Users/sfq/Library/Mobile Documents/com~apple~CloudDocs/roam/`.
<img width="647" alt="Screen Shot 2020-06-27 at 11 24 12 AM" src="https://user-images.githubusercontent.com/5546074/85914082-b8862800-b86c-11ea-8a9d-b802e2f03eed.png">

**Comment by jethrokuan** [comment]
I have no idea what an app document is, but would using the elisp implementation of file finding work for you?

```
(setq org-roam-list-files-commands nil)
```

**Comment by fountainer** [comment]
> I have no idea what an app document is, but would using the elisp implementation of file finding work for you?
> 
> ```
> (setq org-roam-list-files-commands nil)
> ```

It doesn't work.  I noticed that the file name contains an absolute path on the top of the `*org-roam*` bufferm when it doesn't work, as shown in the first screenshot.

**Comment by fountainer** [comment]
I created a soft link. I think this setting may cause this problem.
```bash
ln -nsf /Users/sfq/Library/Mobile\ Documents/iCloud~com~coderforart~iOS~MWeb/Documents ~/iCloudDrive/MWeb
```

**Comment by jethrokuan** [comment]
I'm just unsure if the problem lies with org-roam's file file finding implementation. I suspect that's not the case.

**Comment by myshevchuk** [comment]
@fountainer, iCloud documents are not visible in Finder, but are accessible from the command line (and Emacs) as `~/Documents`. Their actual location is `~/Documents`, so you can simply use ~/Documents in Emacs.

**Comment by fountainer** [comment]
@myshevchuk Do you mean the directory `/Users/sfq/Library/Mobile Documents/iCloud~com~coderforart~iOS~MWeb/Documents` is actual `~/Documents/iCloud~com~coderforart~iOS~MWeb/Documents`?  I tried this command`ls ~/Documents/iCloud~com~coderforart~iOS~MWeb/Documents` and it gave an error "No such file or directory".

**Comment by myshevchuk** [comment]
@fountainer, no I mean your normal Documents folder you access from Finder>iCloud Drive>Documents is `/Users/sfq/Documents`. Should be at least. What version of MacOs are you running?

**Comment by fountainer** [comment]
@myshevchuk The version of my MacOS is 15.5.5. 
<img width="692" alt="Screen Shot 2020-07-26 at 11 56 20 PM" src="https://user-images.githubusercontent.com/5546074/88483628-ae566700-cf9b-11ea-9c9b-aa541a2e2c4a.png"> 
For Finder>iCloud Drive>MWeb, do you mean I can access it using `/Users/sfq/MWeb`? I tried "ls /User/sfq/MWeb" and the error still occurs.

**Comment by myshevchuk** [comment]
@fountainer Sorry, I wasn't very clear and made wrong initial assumptions about your setup. I don't know what's causing your issue, but I got things working as follows (i used beorg app instead of MWeb, I believe it doesn't matter):

1. Create a symlink `ln -s ~/Library/Mobile\ Documents/iCloud\~com\~appsonthemove\~beorg/Documents/roam ~/roam`
2. Set org-roam directory as follows `(setq org-roam-directory (file-truename ~/roam)`
3. Restart Emacs
4. Create files `Test1` and `Test2`, insert an org-roam link in `Test2` pointing to `Test1`
5. In org-roam buffer for `Test1` there is a backlink from `Test2`

Note, that I did not set `directory-abbrev-alist`, actually your problem may lie therein: it's docstring says to avoid tildas ~

<img width="1397" alt="Screenshot 2020-07-26 at 20 23 58" src="https://user-images.githubusercontent.com/24212814/88486646-77725800-cf7f-11ea-8acc-282362cec982.png">

**Comment by fountainer** [comment]
@myshevchuk I used `dirctory-abbrev-alist` because I want to shorten pathnames listed by commands, such as `counsel-recentf`. For this purpose, I set `directory-abbrev-alist` as `("/Users/sfq/Library/Mobile Documents/iCloud~com~coderforart~iOS~MWeb/Documents" . "~/iCloudDrive/MWeb"))`. Replacing `~` with `/Users/sfq` doesn't solve the problem of no backlinks.

**Comment by myshevchuk** [comment]
@fountainer @jethrokuan I can confirm setting `directory-abbrev-alist` breaks org-roam backlinks.

Steps to reproduce
1. 
```sh
ln -s /absolute/path/to/roam /symlink/path/to/roam
```
2. 
```elisp
(setq org-roam-directory "/symlink/path/to/roam")
or 
(setq org-roam-directory (file-truename "/symlink/path/to/roam"))

(setq directory-abbrev-alist '(("^/absolute/path/to/roam" . "/symlink/path/to/roam"))
```
3. Rebuild cache, restart Emacs
4. Backlinks are broken, titles in the org-roam buffer is of form `../../../path/to/roam/file` with a varying number of `../` depending on the actual directory nesting.
5. Citelinks seem to be fine.

This is clearly an issue because using the core Emacs functionality break Org Roam.

**Comment by myshevchuk** [comment]
@fountainer As a temporary solution, try unsetting `directory-abbrev-alis`

**Comment by anildigital** [comment]
@myshevchuk for me 
```elisp
(print directory-abbrev-alist)
```
prints `nil`
and issue still exist

**Comment by Yevgnen** [comment]
Any update of this?
