### ISSUE TITLE
Split after-finalize hook used by `org-roam-insert` and `org-roam-find-file`

### ISSUE THREAD

**Issue by zaeph** [org-roam/org-roam#930]
Prompted by #929.

#482 introduced `after-finalize` hooks to `org-roam-capture`.  The problem is that it's used both by `org-roam-find-file` and `org-roam-insert`, and the finalising of the two does not imply the same exit behaviour, especially concerning the windows.

**Comment by edgimar** [comment]
Though not exactly the same issue, I think this is related and relevant to this issue:

I am currently using `defadvice` in the way described [here](https://stackoverflow.com/a/66055352) to force `org-capture` to open in a new frame.  The problem with how org-roam is doing things is that everything ultimately uses `org-capture` including `org-roam-find-file`.  So the problem is that whatever advice added to `org-capture` is applied also for `org-roam-find-file`.  There needs to be a way to separate the two so that `org-roam-find-file` doesn't open in a new frame, but `org-capture` does.
